"""``apply(text, ops, span)``: operations on an entry file's text (ADR-0042 P1).

ADR-0042 decisions 1, 2, 3 and 6, amendment A4; #730 section 1 and phase P1.
The function is pure and not wired to any write path yet (P3 does that).

The fixtures are the 17 hand-made shapes of #730 section 1, written here by
hand as string literals, never generated by Pyrite. They are string literals
rather than files because several shapes are bytes the repo's pre-commit hooks
would "fix" in a file: CRLF, a BOM, trailing spaces, a body with no final
newline.

The oracle is independent of the module under test:

- the reader parses before and after (``load_frontmatter``, the split every read
  uses);
- the expected value is the operations applied to the parsed dict by
  ``_expected`` below;
- the bytes outside the spans an operation names are compared, before against
  after, by ``tests/file_operations_oracle.py``: its own span rule and its own
  mechanism (an indentation scan for where block values end), never the
  module's (Andon #745: an earlier oracle here was the module's scan copied);
- equality is ``_eq``, ADR-0042 decision 3 written out again here.

Each guard the module adds has a test that fails when that guard alone is
removed. They are listed in the PR.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any

import pytest

from pyrite.exceptions import FrontmatterError
from pyrite.utils.frontmatter import Frontmatter, load_frontmatter, split_frontmatter
from tests.file_operations_oracle import op_spans, outside_identical
from pyrite.storage.file_operations import (
    AddSubkey,
    Append,
    FrontmatterSpan,
    OperationRefusedError,
    Remove,
    ReplaceBody,
    Set,
    Unset,
    apply,
    values_equal,
)

# --- the 17 shapes (#730 section 1) -----------------------------------------

SHAPES: dict[str, str] = {
    # 1. the doc's first example (docs/how-pyrite-edits-your-files.md)
    "doc-field-notes": (
        "---\n"
        "# reviewed by hand, do not reorder\n"
        "id: field-notes\n"
        "title: Field notes   # working title\n"
        "type: note\n"
        "\n"
        "tags: [alpha, beta]\n"
        "links:\n"
        "- target: other-entry\n"
        "  relation: related\n"
        "flag: no\n"
        "---\n"
        "\n"
        "    an indented first line\n"
        "\n"
        "Text.\n"
    ),
    # 2. the doc's second example: a hand-written link in a legacy spelling
    "doc-legacy-links": (
        "---\n"
        "id: legacy-links\n"
        "title: Legacy links\n"
        "type: note\n"
        "links:\n"
        "- to: foo          # legacy spelling, hand written\n"
        "  type: related\n"
        "  since: 2020\n"
        "---\n"
        "\n"
        "Text.\n"
    ),
    # 3. CRLF line endings
    "crlf": (
        "---\r\n"
        "# header comment\r\n"
        "id: echo-me\r\n"
        'title: "Quoted title"\r\n'
        "type: note\r\n"
        "date: 2026-01-15\r\n"
        "tags: [alpha, beta]  # trailing\r\n"
        "---\r\n"
        "\r\n"
        "Body.\r\n"
    ),
    # 4. a byte-order mark
    "bom": ("﻿---\nid: bom\ntitle: With a BOM\ntags:\n- a\n- b\n---\n\nText.\n"),
    # 5. a single-quoted scalar with an escaped quote and a '#', and a comment
    "quoted": (
        "---\n"
        "id: quoted\n"
        "title: 'it''s the #1 hit'   # c\n"
        'summary: "say \\"hi\\""\n'
        "---\n"
        "\n"
        "Text.\n"
    ),
    # 6. bare words a YAML 1.1 reader would misread; Pyrite reads YAML 1.2
    "yaml11-words": (
        "---\nid: words\nflag: no\nother: yes\nnil: null\nstatus: draft\n---\n\nText.\n"
    ),
    # 7. block scalars: folded, then literal, then a plain key
    "block-scalars": (
        "---\n"
        "id: folded\n"
        "summary: >\n"
        "  a folded\n"
        "  paragraph\n"
        "\n"
        "notes: |\n"
        "  line one\n"
        "  line two\n"
        "next: 1\n"
        "---\n"
        "\n"
        "Text.\n"
    ),
    # 8. a plain scalar that runs over two lines
    "multiline-plain": (
        "---\nid: multi\ntitle: a plain scalar\n  that wraps\nother: x\n---\n\nText.\n"
    ),
    # 9. a zero-indent list next to an indented list
    "mixed-list-indent": (
        "---\nid: mixed\ntags:\n- a\n- b\naliases:\n  - x\n  - y\n---\n\nText.\n"
    ),
    # 10. an anchor, an alias and a merge key
    "anchor-alias": (
        "---\n"
        "id: anchored\n"
        "base: &b\n"
        "  k: v\n"
        "child: *b\n"
        "merged:\n"
        "  <<: *b\n"
        "  own: 1\n"
        "plain: ok\n"
        "---\n"
        "\n"
        "Text.\n"
    ),
    # 11. duplicate keys
    "duplicate-keys": ("---\nid: dup\ntitle: one\ntitle: two\nstatus: draft\n---\n\nText.\n"),
    # 12. a Hugo post: 4-space nested map, RFC 3339 date, shortcode body, no id
    "hugo": (
        "---\n"
        'title: "My first post"\n'
        "date: 2024-03-01T09:30:00-05:00\n"
        "draft: false\n"
        "params:\n"
        "    author: Jane\n"
        "    social:\n"
        "        twitter: jane\n"
        'tags: ["hugo", "notes"]\n'
        "---\n"
        "\n"
        '{{< figure src="/img/a.png" caption="A" >}}\n'
        "\n"
        "Body text.\n"
    ),
    # 13. a comment above a key that gets unset
    "comment-above-unset": (
        "---\n"
        "id: commented\n"
        "title: T\n"
        "# the next key is deprecated\n"
        "legacy: old\n"
        "status: draft\n"
        "---\n"
        "\n"
        "Text.\n"
    ),
    # 14. a body with no trailing newline
    "no-final-newline": "---\nid: nonl\ntitle: T\n---\n\nText without a newline",
    # 15. odd spacing: wide gap after a key, trailing spaces, a 4-space list
    "odd-spacing": (
        "---\nid:    odd\ntitle: Trailing space   \ntags:\n    - one\n    - two\n---\n\nText.\n"
    ),
    # 16. an empty flow list and an empty flow map
    "empty-flow": "---\nid: empty\ntags: []\nlinks: {}\n---\n\nText.\n",
    # 17. a date, and a date written as a quoted string
    "dates": ("---\nid: dated\ndate: 2026-01-15\nupdated: '2026-01-16'\n---\n\nText.\n"),
}


# --- the test's own frontmatter span, checked against the reader ------------


def span_of(text: str) -> FrontmatterSpan | None:
    """Where ``text``'s YAML frontmatter is: the caller's job in production, here
    ``split_frontmatter`` (pyrite.utils.frontmatter), the one rule. Checked against the
    reader's parse so this helper cannot drift from it unnoticed."""
    split = split_frontmatter(text)
    if not isinstance(split, Frontmatter):
        return None
    span = FrontmatterSpan(split.yaml_start, split.close_start, split.close_end)
    try:
        parsed = load_frontmatter(text)
    except FrontmatterError:  # duplicate keys: the reader refuses
        return span
    assert parsed is not None
    assert parsed[1] == text[span.body :].strip()
    return span


def run(text: str, *ops: Any):
    return apply(text, list(ops), span_of(text))


# --- the independent oracle --------------------------------------------------


def _eq(a: Any, b: Any) -> bool:
    """ADR-0042 decision 3, written again from the ADR, for the oracle."""
    if isinstance(a, bool) or isinstance(b, bool):
        return type(a) is bool and type(b) is bool and a == b
    if a is None or b is None:
        return a is None and b is None
    if isinstance(a, int | float) and isinstance(b, int | float):
        return a == b or (a != a and b != b)  # NaN is a value: .nan equals .nan (#749)
    if isinstance(a, str) and isinstance(b, date | datetime):
        a, b = b, a
    if isinstance(a, date | datetime) and isinstance(b, str):
        if a.isoformat() == b or (isinstance(a, datetime) and a.isoformat(" ") == b):
            return True
        if isinstance(a, datetime):
            try:
                other = datetime.fromisoformat(b)
            except ValueError:
                return False
            if (a.tzinfo is None) != (other.tzinfo is None):
                return False
            return a == other
        return False
    if isinstance(a, dict) and isinstance(b, dict):
        return set(a) == set(b) and all(_eq(a[k], b[k]) for k in a)
    if isinstance(a, list) and isinstance(b, list):
        return len(a) == len(b) and all(_eq(x, y) for x, y in zip(a, b, strict=True))
    if type(a) is not type(b) and not (isinstance(a, str) and isinstance(b, str)):
        return False
    return a == b


def _plain(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(k): _plain(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_plain(v) for v in value]
    if type(value).__name__ == "ScalarBoolean":
        return bool(value)
    if isinstance(value, datetime) and type(value) is not datetime:
        # ruamel's TimeStamp loses its tzinfo under copy.deepcopy
        return datetime.fromisoformat(value.isoformat())
    return value


def _reader(text: str) -> tuple[dict, str]:
    parsed = load_frontmatter(text)
    assert parsed is not None, "the reader finds no frontmatter in the result"
    return _plain(dict(parsed[0])), parsed[1]


def _segments(path: Any) -> list:
    if isinstance(path, tuple | list):
        return list(path)
    out: list = []
    for part in path.split("."):
        name, _, rest = part.partition("[")
        if name:
            out.append(name)
        while rest:
            index, _, rest = rest.partition("]")
            out.append(int(index))
            rest = rest[1:] if rest.startswith("[") else rest
    return out


def _expected(meta: dict, op: Any) -> dict:
    """The operation applied to the parsed value, by hand."""
    import copy

    result = copy.deepcopy(meta)
    if isinstance(op, ReplaceBody):
        return result
    segs = _segments(op.path)
    if isinstance(op, AddSubkey):
        segs = [*segs, op.key]
    parent: Any = result
    for seg in segs[:-1]:
        if isinstance(parent, dict) and (seg not in parent or parent[seg] is None):
            if isinstance(op, Unset | Remove):
                return result
            parent[seg] = {}
        parent = parent[seg]
    last = segs[-1]
    if isinstance(op, Set | AddSubkey):
        if isinstance(parent, dict) and last in parent and _eq(parent[last], op.value):
            return result
        parent[last] = op.value
    elif isinstance(op, Unset):
        if isinstance(parent, dict):
            parent.pop(last, None)
        else:
            del parent[last]
    elif isinstance(op, Append):
        if parent.get(last) is None:
            parent[last] = []
        parent[last].append(op.value)
    elif isinstance(op, Remove):
        items = parent.get(last) or []
        for i, item in enumerate(items):
            if _eq(item, op.value):
                del items[i]
                break
    return result


def check_contract(before: str, ops: list, after: str, narrow: bool = True) -> None:
    """The contract for any result, one operation at a time:

    - every byte outside the spans the operation names is identical, before
      against after (``file_operations_oracle``: its own span rule and
      mechanism, not the module's);
    - the reader gets exactly the operations applied, with key order kept and
      new keys last;
    - the BOM, the body (unless replaced) and the line endings are kept.

    Every step one by one must pass on its own and stay narrow (no widen: the
    edits these tests make all have a narrow form). A call with several
    operations reads the same as applying them one by one. Its bytes equal
    them too, except for one stated limit (L3, module docstring): a batch of
    operations on different top-level keys indents newly emitted lines by the
    file's conventions *before* the batch, one by one by the conventions after
    each step; there the call is checked against all its spans in the
    original."""
    step = before
    tops = set()
    for op in ops:
        nxt, report = apply(step, [op], span_of(step))
        assert not narrow or report.widened == (), f"{op}: widened on an edit with a narrow form"
        spans = op_spans(step, span_of(step), op)
        assert outside_identical(step, nxt, spans), (
            f"{op}: bytes outside its spans {spans} changed:\n{_diff(step, nxt)}"
        )
        step = nxt
        tops.add(None if isinstance(op, ReplaceBody) else str(_segments(op.path)[0]))
    if after != step:
        assert len(tops) == len(ops), "the call differs from its operations applied one by one"
        spans = [sp for op in ops for sp in op_spans(before, span_of(before), op)]
        assert outside_identical(before, after, spans), _diff(before, after)
    meta, body = _reader(before)
    expected = meta
    for op in ops:
        expected = _expected(expected, op)
    got, new_body = _reader(after)
    assert _eq(got, expected), f"parsed {got!r}, expected {expected!r}"
    assert list(got) == list(expected), "key order changed"
    if not any(isinstance(op, ReplaceBody) for op in ops):
        assert after[span_of(after).body :] == before[span_of(before).body :]
    assert after.startswith("\ufeff") == before.startswith("\ufeff")
    if "\r\n" in before:
        assert after.count("\n") == after.count("\r\n"), "a bare LF in a CRLF file"
    else:
        assert "\r" not in after


# --- the table: every shape crossed with the operations -----------------------

CASES: list[tuple[str, list, str]] = [
    # (shape, ops, outcome): outcome is "changed", "unchanged" or "refused"
    ("doc-field-notes", [Set("title", "Field notes, second draft")], "changed"),
    ("doc-field-notes", [Set("flag", "yes")], "changed"),
    ("doc-field-notes", [Set("flag", "no")], "unchanged"),
    ("doc-field-notes", [Append("tags", "gamma")], "changed"),
    ("doc-field-notes", [Remove("tags", "alpha")], "changed"),
    ("doc-field-notes", [Set("links[0].relation", "supersedes")], "changed"),
    ("doc-field-notes", [AddSubkey("links[0]", "note", "x")], "changed"),
    ("doc-field-notes", [Unset("type")], "changed"),
    ("doc-field-notes", [Set("importance", 3)], "changed"),
    ("doc-field-notes", [ReplaceBody("New body.")], "changed"),
    ("doc-field-notes", [Set("tags", ["alpha", "beta"])], "unchanged"),
    ("doc-field-notes", [Set("tags", ["beta", "gamma"])], "changed"),
    (
        "doc-field-notes",
        [Set("links", [{"target": "other-entry", "relation": "related"}, {"target": "x"}])],
        "changed",
    ),
    ("doc-legacy-links", [Append("links", {"target": "bar", "relation": "related"})], "changed"),
    ("doc-legacy-links", [Set("links[0].type", "cites")], "changed"),
    (
        "doc-legacy-links",
        [Remove("links", {"to": "foo", "type": "related", "since": 2020})],
        "changed",
    ),
    ("crlf", [Set("title", "New title")], "changed"),
    ("crlf", [Set("status", "draft")], "changed"),
    ("crlf", [Append("tags", "gamma")], "changed"),
    ("crlf", [Set("date", "2026-01-15")], "unchanged"),
    ("crlf", [ReplaceBody("Line one.\nLine two.")], "changed"),
    ("bom", [Set("title", "Still a BOM")], "changed"),
    ("bom", [Append("tags", "c")], "changed"),
    ("bom", [Unset("tags")], "changed"),
    ("quoted", [Set("title", "it's new")], "changed"),
    ("quoted", [Set("summary", 'say "bye"')], "changed"),
    ("yaml11-words", [Set("status", "no")], "changed"),
    ("yaml11-words", [Set("other", True)], "changed"),
    ("yaml11-words", [Set("nil", None)], "unchanged"),
    ("yaml11-words", [Set("other", "yes")], "unchanged"),
    ("block-scalars", [Unset("summary")], "changed"),
    ("block-scalars", [Unset("notes")], "changed"),
    ("block-scalars", [Set("notes", "line one\nline three\n")], "changed"),
    ("block-scalars", [Set("summary", "a new folded paragraph\n")], "changed"),
    ("block-scalars", [Set("next", 2)], "changed"),
    ("multiline-plain", [Set("other", "y")], "changed"),
    ("multiline-plain", [Set("title", "short")], "changed"),
    ("mixed-list-indent", [Append("tags", "c")], "changed"),
    ("mixed-list-indent", [Append("aliases", "z")], "changed"),
    ("mixed-list-indent", [Remove("aliases", "x")], "changed"),
    ("anchor-alias", [Set("plain", "new")], "changed"),
    ("anchor-alias", [Set("base.k", "w")], "refused"),
    ("anchor-alias", [Set("child", {"k": "w"})], "refused"),
    ("anchor-alias", [Set("merged.own", 2)], "refused"),
    ("anchor-alias", [Unset("child")], "refused"),
    ("duplicate-keys", [Set("title", "three")], "refused"),
    ("duplicate-keys", [Set("status", "done")], "refused"),
    ("hugo", [Set("params.author", "John")], "changed"),
    ("hugo", [Set("params.social.mastodon", "@jane")], "changed"),
    ("hugo", [Set("draft", True)], "changed"),
    ("hugo", [Append("tags", "go")], "changed"),
    ("hugo", [Set("date", "2024-03-01T14:30:00+00:00")], "unchanged"),
    ("hugo", [Set("date", "2024-03-02T09:30:00-05:00")], "changed"),
    ("hugo", [ReplaceBody('{{< figure src="/img/b.png" >}}\n\nNew text.')], "changed"),
    ("comment-above-unset", [Unset("legacy")], "changed"),
    ("comment-above-unset", [Set("metadata.source_id", "s-1")], "changed"),
    ("no-final-newline", [ReplaceBody("Other text")], "changed"),
    ("no-final-newline", [Set("title", "U")], "changed"),
    ("odd-spacing", [Set("title", "New")], "changed"),
    ("odd-spacing", [Append("tags", "three")], "changed"),
    ("odd-spacing", [Set("id", "odd")], "unchanged"),
    ("empty-flow", [Append("tags", "a")], "changed"),
    ("empty-flow", [Set("links.k", 1)], "changed"),
    ("empty-flow", [Unset("tags")], "changed"),
    ("dates", [Set("date", "2026-01-15")], "unchanged"),
    ("dates", [Set("date", "2026-02-01")], "changed"),
    ("dates", [Set("updated", "2026-01-17")], "changed"),
    ("dates", [Set("updated", "2026-01-16")], "unchanged"),
    ("dates", [Unset("missing")], "unchanged"),
    ("dates", [Remove("tags", "x")], "unchanged"),
]


def test_every_shape_is_in_the_table():
    """Property 7: each of #730's 17 shapes is exercised."""
    assert len(SHAPES) == 17
    assert {shape for shape, _, _ in CASES} == set(SHAPES)


@pytest.mark.parametrize(
    ("shape", "ops", "outcome"),
    CASES,
    ids=[f"{s}-{i}" for i, (s, _, _) in enumerate(CASES)],
)
def test_operation_contract(shape, ops, outcome):
    before = SHAPES[shape]
    if outcome == "refused":
        with pytest.raises(OperationRefusedError) as raised:
            run(before, *ops)
        assert raised.value.reason
        return
    after, report = run(before, *ops)
    if outcome == "unchanged":
        assert after is before
        assert not report.changed
        assert [r.outcome for r in report.results] == ["unchanged"] * len(ops)
        return
    assert after != before
    assert report.changed
    check_contract(before, ops, after)


# --- exact bytes: quote style, comment column, EOL, BOM, list style -----------


def _diff(before: str, after: str) -> list[str]:
    import difflib

    a, b = before.splitlines(keepends=True), after.splitlines(keepends=True)
    return [
        line
        for line in difflib.unified_diff(a, b, n=0)
        if line[:1] in "+-" and not line.startswith(("+++", "---"))
    ]


def test_doc_example_one_field_edit_keeps_the_comment():
    after, _ = run(SHAPES["doc-field-notes"], Set("title", "Field notes, second draft"))
    assert _diff(SHAPES["doc-field-notes"], after) == [
        "-title: Field notes   # working title\n",
        "+title: Field notes, second draft   # working title\n",
    ]


def test_doc_example_append_leaves_existing_items_alone():
    before = SHAPES["doc-legacy-links"]
    after, _ = run(before, Append("links", {"target": "bar", "relation": "related"}))
    assert _diff(before, after) == ["+- target: bar\n", "+  relation: related\n"]


def test_a_shorter_value_keeps_the_comment_column():
    before = SHAPES["quoted"]
    after, _ = run(before, Set("title", "it's new"))
    line = after.splitlines()[2]
    assert line == "title: 'it''s new'          # c"
    assert line.rindex("#") == before.splitlines()[2].rindex("#")


def test_a_double_quoted_scalar_stays_double_quoted():
    after, _ = run(SHAPES["crlf"], Set("title", "New title"))
    assert _diff(SHAPES["crlf"], after) == [
        '-title: "Quoted title"\r\n',
        '+title: "New title"\r\n',
    ]


def test_a_new_key_goes_last_with_the_files_line_ending():
    after, _ = run(SHAPES["crlf"], Set("status", "draft"))
    assert after.endswith(
        "tags: [alpha, beta]  # trailing\r\nstatus: draft\r\n---\r\n\r\nBody.\r\n"
    )


def test_a_flow_list_append_copies_its_neighbours_quoting():
    after, _ = run(SHAPES["hugo"], Append("tags", "go"))
    assert 'tags: ["hugo", "notes", "go"]\n' in after


def test_an_append_takes_each_lists_own_indent():
    before = SHAPES["mixed-list-indent"]
    after, _ = run(before, Append("tags", "c"), Append("aliases", "z"))
    assert _diff(before, after) == ["+- c\n", "+  - z\n"]


def test_a_nested_set_keeps_four_space_indent():
    before = SHAPES["hugo"]
    after, _ = run(before, Set("params.social.mastodon", "@jane"))
    assert _diff(before, after) == ['+        mastodon: "@jane"\n']


def test_a_string_yaml11_would_misread_is_quoted_when_emitted():
    before = SHAPES["yaml11-words"]
    after, _ = run(before, Set("status", "no"))
    assert _diff(before, after) == ["-status: draft\n", '+status: "no"\n']
    assert "flag: no\nother: yes\nnil: null\n" in after


def test_untouched_yes_no_null_stay_bare():
    before = SHAPES["yaml11-words"]
    after, _ = run(before, Set("status", "done"))
    assert "flag: no\nother: yes\nnil: null\n" in after


def test_the_bom_survives_every_operation():
    before = SHAPES["bom"]
    after, _ = run(before, Set("title", "Still"), Append("tags", "c"), ReplaceBody("New."))
    assert after.startswith("﻿---\n")


def test_unset_of_a_folded_block_scalar_keeps_the_next_key():
    """#730 section 1, note 2: a block scalar's end mark is at the start of the
    line after it, and the first spike's unset ate the next key."""
    before = SHAPES["block-scalars"]
    after, _ = run(before, Unset("summary"))
    assert _diff(before, after) == [
        "-summary: >\n",
        "-  a folded\n",
        "-  paragraph\n",
    ]
    assert "\nnotes: |\n  line one\n  line two\nnext: 1\n" in after


def test_unset_of_a_literal_block_scalar_keeps_the_next_key():
    before = SHAPES["block-scalars"]
    after, _ = run(before, Unset("notes"))
    assert _diff(before, after) == ["-notes: |\n", "-  line one\n", "-  line two\n"]


def test_set_of_a_literal_block_scalar_keeps_literal_style():
    before = SHAPES["block-scalars"]
    after, _ = run(before, Set("notes", "line one\nline three\n"))
    assert _diff(before, after) == ["-  line two\n", "+  line three\n"]


def test_unset_leaves_the_comment_above_the_key():
    before = SHAPES["comment-above-unset"]
    after, _ = run(before, Unset("legacy"))
    assert _diff(before, after) == ["-legacy: old\n"]


def test_unset_of_a_list_does_not_take_the_comment_after_it():
    """A block sequence's end mark runs past the comment line below it."""
    before = "---\nid: c\ntags:\n- a\n- b\n# about status\nstatus: x\n---\n\nT.\n"
    after, _ = run(before, Unset("tags"))
    assert _diff(before, after) == ["-tags:\n", "-- a\n", "-- b\n"]


def test_removing_the_last_item_of_a_block_list_leaves_an_empty_list():
    before = "---\nid: c\ntags:\n- a\n---\n\nT.\n"
    after, _ = run(before, Remove("tags", "a"))
    assert _reader(after)[0]["tags"] == []


def test_a_set_of_a_list_is_reduced_to_item_edits():
    before = SHAPES["doc-legacy-links"]
    new_links = [
        {"to": "foo", "type": "related", "since": 2020},
        {"target": "bar", "relation": "related"},
    ]
    after, _ = run(before, Set("links", new_links))
    assert _diff(before, after) == ["+- target: bar\n", "+  relation: related\n"]


def test_add_subkey_inserts_one_line_at_the_items_indent():
    before = SHAPES["doc-field-notes"]
    after, _ = run(before, AddSubkey("links[0]", "note", "x"))
    assert _diff(before, after) == ["+  note: x\n"]


def test_add_subkey_refuses_an_existing_key_with_another_value():
    with pytest.raises(OperationRefusedError):
        run(SHAPES["doc-field-notes"], AddSubkey("links[0]", "relation", "other"))


def test_replace_body_keeps_the_leading_blank_line_and_missing_newline():
    before = SHAPES["no-final-newline"]
    after, _ = run(before, ReplaceBody("Other text"))
    assert after == "---\nid: nonl\ntitle: T\n---\n\nOther text"


def test_replace_body_in_a_crlf_file_writes_crlf():
    after, _ = run(SHAPES["crlf"], ReplaceBody("Line one.\nLine two."))
    assert after.endswith("---\r\n\r\nLine one.\r\nLine two.\r\n")


def test_replace_body_with_the_readers_form_is_unchanged():
    before = SHAPES["doc-field-notes"]
    body = _reader(before)[1]
    after, report = run(before, ReplaceBody(body))
    assert after is before and not report.changed


def test_a_date_string_set_keeps_the_date_plain():
    before = SHAPES["dates"]
    after, _ = run(before, Set("date", "2026-02-01"), Set("updated", "2026-01-17"))
    assert _diff(before, after) == [
        "-date: 2026-01-15\n",
        "-updated: '2026-01-16'\n",
        "+date: 2026-02-01\n",
        "+updated: '2026-01-17'\n",
    ]


def test_a_number_into_a_plain_string_field_is_quoted():
    before = SHAPES["doc-field-notes"]
    after, _ = run(before, Set("type", "123"))
    assert '\ntype: "123"\n' in after
    assert _reader(after)[0]["type"] == "123"


def test_several_operations_in_one_call():
    before = SHAPES["doc-field-notes"]
    ops = [Set("title", "T2"), Append("tags", "gamma"), Unset("flag"), ReplaceBody("B.")]
    after, report = run(before, *ops)
    assert [r.outcome for r in report.results] == ["changed"] * 4
    check_contract(before, ops, after)


# --- refusals ---------------------------------------------------------------


@pytest.mark.parametrize(
    "text",
    [
        '+++\ntitle = "TOML"\n+++\n\nText.\n',
        '{\n  "title": "JSON"\n}\n\nText.\n',
        "No frontmatter at all.\n",
    ],
    ids=["toml", "json", "none"],
)
def test_no_yaml_frontmatter_is_refused_untouched(text):
    with pytest.raises(OperationRefusedError) as raised:
        apply(text, [Set("title", "x")], span_of(text))
    assert raised.value.reason


def test_a_flow_style_root_mapping_is_refused():
    text = "---\n{id: x, title: y}\n---\n\nText.\n"
    with pytest.raises(OperationRefusedError):
        run(text, Set("title", "z"))


def test_an_append_to_a_scalar_is_refused():
    with pytest.raises(OperationRefusedError):
        run(SHAPES["doc-field-notes"], Append("title", "x"))


def test_the_anchor_refusal_names_the_reason():
    with pytest.raises(OperationRefusedError) as raised:
        run(SHAPES["anchor-alias"], Set("child", {"k": "w"}))
    assert "anchor" in raised.value.reason or "alias" in raised.value.reason


def test_the_duplicate_key_refusal_names_the_key():
    """Refused by the module's own check, in one line a person can read; not
    by ruamel's multi-line DuplicateKeyError, which the loader would raise
    anyway."""
    with pytest.raises(OperationRefusedError) as raised:
        run(SHAPES["duplicate-keys"], Set("status", "done"))
    assert "duplicate key 'title'" in raised.value.reason
    assert "\n" not in raised.value.reason


# --- property 5: a no-op returns the very same object ------------------------


@pytest.mark.parametrize("shape", sorted(SHAPES))
def test_no_operations_return_the_input_object(shape):
    text = SHAPES[shape]
    after, report = apply(text, [], span_of(text))
    assert after is text and not report.changed


@pytest.mark.parametrize("shape", sorted(set(SHAPES) - {"anchor-alias", "duplicate-keys"}))
def test_an_echo_of_every_value_is_a_no_op(shape):
    """Setting every top-level key to the value the reader gives writes nothing."""
    text = SHAPES[shape]
    meta, body = _reader(text)
    ops = [Set(key, value) for key, value in meta.items()] + [ReplaceBody(body)]
    after, report = run(text, *ops)
    assert after is text
    assert not report.changed


# --- the post-check is the guard (ADR-0042 decision 2) ------------------------


def test_a_narrow_edit_that_fails_the_post_check_is_widened_not_returned(monkeypatch):
    """A narrow edit that also changes bytes it was not asked to change must
    never be returned: the post-check catches it and the key is widened
    item-wise (or the call refuses)."""
    from pyrite.storage import file_operations as fo

    real = fo._narrow_edits

    def corrupt(doc, op):
        edits = real(doc, op)
        # also respell an untouched key: `type: note` -> `type: Note`
        at = doc.text.index("type: note") + len("type: ")
        return [*edits, (at, at + 1, "N")]

    monkeypatch.setattr(fo, "_narrow_edits", corrupt)
    before = SHAPES["doc-field-notes"]
    try:
        after, report = run(before, Append("links", {"target": "x"}))
    except OperationRefusedError:
        return
    assert "type: note\n" in after
    check_contract(before, [Append("links", {"target": "x"})], after, narrow=False)
    assert report.widened == ("links",)


def test_a_narrow_edit_that_breaks_the_value_is_widened(monkeypatch):
    """The post-check compares values too, not only untouched bytes."""
    from pyrite.storage import file_operations as fo

    real = fo._narrow_edits

    def corrupt(doc, op):
        return [(s, e, r.replace("bar", "baz")) for s, e, r in real(doc, op)]

    monkeypatch.setattr(fo, "_narrow_edits", corrupt)
    before = SHAPES["doc-legacy-links"]
    op = Append("links", {"target": "bar", "relation": "related"})
    after, report = run(before, op)
    check_contract(before, [op], after, narrow=False)
    assert report.widened == ("links",)
    # item-wise: the hand-written item, comment and all, is copied by bytes
    assert _diff(before, after) == ["+- target: bar\n", "+  relation: related\n"]


def test_values_equal_is_decision_3():
    assert values_equal("2026-01-15", date(2026, 1, 15))
    assert values_equal(1, 1.0)
    assert not values_equal(True, 1)
    assert values_equal({"a": 1, "b": 2}, {"b": 2, "a": 1})
    assert not values_equal([1, 2], [2, 1])
    assert not values_equal("5", 5)


# --- the oracle can see failures: candidate A as a control --------------------


def _round_trip(text: str, key: str, value: Any) -> str:
    """#730's candidate A: load with ruamel, set, dump. Rejected by the spike
    for respelling bytes nobody asked to change."""
    from pyrite.utils.yaml import dump_yaml, load_yaml

    span = span_of(text)
    data = load_yaml(text[span.start : span.end])
    data[key] = value
    return text[: span.start] + dump_yaml(data) + text[span.end :]


@pytest.mark.parametrize(
    ("shape", "key", "value"),
    [
        ("hugo", "draft", True),  # re-indents the 4-space params map
        ("yaml11-words", "status", "done"),  # respells `nil: null` as `nil:`
        ("odd-spacing", "title", "New"),  # collapses `id:    odd`
    ],
)
def test_the_oracle_catches_the_round_trip(shape, key, value):
    """The contract check is not vacuous: the round trip fails it where the
    spike saw it change untouched bytes, and apply passes it."""
    before = SHAPES[shape]
    with pytest.raises(AssertionError):
        check_contract(before, [Set(key, value)], _round_trip(before, key, value))
    after, _ = run(before, Set(key, value))
    check_contract(before, [Set(key, value)], after)


# --- round 1 (#732): a value-level patch; comments belong to no value ---------


def _apply1(text: str, *ops: Any) -> str:
    return run(text, *ops)[0]


def test_unset_of_a_dash_line_pair_keeps_the_comment_below_it():
    """The comment line between the unset pair and its kept sibling is not
    the unset pair's (cold read, p1)."""
    before = "---\nlinks:\n- target: a\n  # note about relation\n  relation: b\n---\nx\n"
    after = _apply1(before, Unset("links[0].target"))
    assert "  # note about relation\n" in after
    assert _reader(after)[0] == {"links": [{"relation": "b"}]}
    check_contract(before, [Unset("links[0].target")], after)


def test_unset_of_a_dash_line_pair_pulls_the_next_key_up():
    before = "---\nlinks:\n- target: a\n  relation: b\n---\nx\n"
    assert _apply1(before, Unset("links[0].target")) == "---\nlinks:\n- relation: b\n---\nx\n"


@pytest.mark.parametrize(
    ("value", "line"),
    [
        ([], "tags: [] # my tags\n"),
        ("none", "tags: none # my tags\n"),
        ({}, "tags: {} # my tags\n"),
    ],
)
def test_a_block_value_set_inline_keeps_the_key_line_comment(value, line):
    """The comment on a key line is the pair's, not the value's (cold read)."""
    before = "---\ntags: # my tags\n- a\n- b\nz: 1\n---\nx\n"
    after = _apply1(before, Set("tags", value))
    assert after == f"---\n{line}z: 1\n---\nx\n"
    check_contract(before, [Set("tags", value)], after)


def test_a_scalar_set_to_a_block_keeps_its_comment_on_the_key_line():
    before = "---\ntags: foo  # my tags\nz: 1\n---\nx\n"
    after = _apply1(before, Set("tags", ["a", "b"]))
    assert after == "---\ntags:  # my tags\n- a\n- b\nz: 1\n---\nx\n"


def test_a_block_scalar_header_comment_stays():
    before = "---\ns: |  # keep\n  one\nz: 1\n---\nx\n"
    assert _apply1(before, Set("s", "two\n")) == "---\ns: |  # keep\n  two\nz: 1\n---\nx\n"
    assert _apply1(before, Set("s", 3)) == "---\ns: 3  # keep\nz: 1\n---\nx\n"


def test_unset_of_the_first_key_keeps_the_comment_above_the_next():
    before = "---\na: 1\n# about b\nb: 2\n---\nx\n"
    assert _apply1(before, Unset("a")) == "---\n# about b\nb: 2\n---\nx\n"


# The post-check compares the bytes outside the named spans, directly. Each
# fault below is injected into the narrow edit; the result must never carry it.

_GUARDED = '---\na: 1\n# keep me: important\n\n"x:y": 1\nx: 2\n# rule\nlist:\n- a\n---\nbody\n'


@pytest.mark.parametrize(
    ("fault", "target"),
    [
        ("delete a comment line between untouched keys", "# keep me: important\n"),
        ("rewrite a comment", "# rule"),
        ("re-quote a key the scan would confuse with x", '"x:y": 1'),
        ("delete a blank line", "\n\n"),
    ],
)
def test_a_narrow_edit_touching_bytes_outside_its_span_is_never_returned(
    monkeypatch, fault, target
):
    from pyrite.storage import file_operations as fo

    real = fo._narrow_edits
    replacement = {
        "# keep me: important\n": "",
        "# rule": "# RULE",
        '"x:y": 1': "'x:y': 1",
        "\n\n": "\n",
    }[target]

    def corrupt(doc, op):
        at = doc.text.index(target)
        return [*real(doc, op), (at, at + len(target), replacement)]

    monkeypatch.setattr(fo, "_narrow_edits", corrupt)
    op = Append("list", "b")
    after, report = run(_GUARDED, op)
    assert target in after, fault
    assert report.widened == ("list",)
    check_contract(_GUARDED, [op], after, narrow=False)


def test_a_fault_on_a_scalar_that_cannot_widen_is_refused(monkeypatch):
    """A top-level scalar has no item-wise widen: refused, with a reason
    (the widen used to raise AttributeError here)."""
    from pyrite.storage import file_operations as fo

    real = fo._narrow_edits

    def corrupt(doc, op):
        at = doc.text.index("# rule")
        return [*real(doc, op), (at, at + 1, "")]

    monkeypatch.setattr(fo, "_narrow_edits", corrupt)
    with pytest.raises(OperationRefusedError) as raised:
        run(_GUARDED, Set("a", 2))
    assert "outside" in raised.value.reason or "changed" in raised.value.reason


def test_the_final_check_catches_what_the_per_operation_check_missed(monkeypatch):
    """The second line: once per call, the values through the reader's own
    split, compared without ``_same``. With the per-operation value check
    blinded, a corrupt value inside the span is still refused."""
    from pyrite.storage import file_operations as fo

    real = fo._narrow_edits

    def corrupt(doc, op):
        return [(s, e, r.replace("- b", "- zz")) for s, e, r in real(doc, op)]

    monkeypatch.setattr(fo, "_narrow_edits", corrupt)
    monkeypatch.setattr(fo, "_same", lambda got, expected: True)
    with pytest.raises(OperationRefusedError) as raised:
        run(_GUARDED, Append("list", "b"))
    assert "post-check" in raised.value.reason


@pytest.mark.parametrize(
    ("before", "op", "after"),
    [
        ("---\ns: |-\n  x  \nz: 1\n---\nx\n", Set("s", "y"), "---\ns: |-\n  y\nz: 1\n---\nx\n"),
        (
            "---\ndc:title: x\nb: 1\n---\nx\n",
            Set("dc:title", "y"),
            "---\ndc:title: y\nb: 1\n---\nx\n",
        ),
        ('---\n"a:b": 1\nb: 1\n---\nx\n', Set("a:b", 7), '---\n"a:b": 7\nb: 1\n---\nx\n'),
    ],
    ids=["block-scalar-trailing-spaces", "colon-in-plain-key", "colon-in-quoted-key"],
)
def test_top_level_scalars_the_cold_read_crashed_on(before, op, after):
    assert _apply1(before, op) == after


# Keys whose loaded type is not a string: one lookup rule (_key_matches).

_TYPED_KEYS = "---\ntrue: 1\nfalse: 2\nnull: 3\n7: seven\n2024-01-01: day\nb: 4\n---\nx\n"


@pytest.mark.parametrize(
    ("key", "line"),
    [
        ("true", "true: 1\n"),
        ("false", "false: 2\n"),
        ("null", "null: 3\n"),
        ("7", "7: seven\n"),
        ("2024-01-01", "2024-01-01: day\n"),
    ],
)
def test_unset_finds_a_key_by_what_it_reads_as(key, line):
    after, report = run(_TYPED_KEYS, Unset(key))
    assert report.changed
    assert after == _TYPED_KEYS.replace(line, "")


def test_set_finds_a_bool_key():
    assert _apply1(_TYPED_KEYS, Set("true", 2)) == _TYPED_KEYS.replace("true: 1", "true: 2")


def test_a_segment_naming_two_keys_is_refused():
    with pytest.raises(OperationRefusedError) as raised:
        run("---\ntrue: 1\n'true': 2\n---\nx\n", Set("true", 3))
    assert "two keys" in raised.value.reason


def test_a_new_key_spelled_like_a_bool_is_written_as_a_string():
    after = _apply1("---\na: 1\n---\nx\n", Set("true", 1))
    assert after == '---\na: 1\n"true": 1\n---\nx\n'
    assert _reader(after)[0] == {"a": 1, "true": 1}


def test_true_and_1_are_duplicate_keys_as_the_loader_sees_them():
    with pytest.raises(OperationRefusedError) as raised:
        run("---\ntrue: a\n1: b\n---\nx\n", Set("true", "c"))
    assert "duplicate key" in raised.value.reason


# Limits fixed in round 1, and the ones stated in the module docstring.


def test_a_key_starting_with_a_dash():
    assert _apply1("---\na: 1\n---\nx\n", Set("-x", 1)) == "---\na: 1\n-x: 1\n---\nx\n"


def test_an_indentation_indicator_is_kept():
    before = "---\ns: |2-\n   lead\nz: 1\n---\nx\n"
    after = _apply1(before, Set("s", " lead2"))
    assert after == "---\ns: |2-\n   lead2\nz: 1\n---\nx\n"
    assert _reader(after)[0]["s"] == " lead2"


def test_keep_chomping_is_kept():
    before = "---\ns: |+\n  x\n\nz: 1\n---\nx\n"
    after = _apply1(before, Set("s", "y\n\n"))
    assert after == "---\ns: |+\n  y\n\nz: 1\n---\nx\n"


def test_an_append_after_a_keep_scalar_keeps_its_blank_lines():
    before = "---\nl:\n- y\n- |+\n  x\n\n\nz: 1\n---\nx\n"
    after = _apply1(before, Append("l", "w"))
    assert after == "---\nl:\n- y\n- |+\n  x\n\n\n- w\nz: 1\n---\nx\n"
    assert _reader(after)[0]["l"] == ["y", "x\n\n\n", "w"]
    check_contract(before, [Append("l", "w")], after)


def test_a_line_separator_is_escaped_not_written_bare():
    after = _apply1("---\nt: a\n---\nx\n", Set("t", "a b"))
    assert after == '---\nt: "a\\u2028b"\n---\nx\n'


def test_a_large_float_reads_as_a_float_under_yaml_11_too():
    import yaml

    after = _apply1("---\nn: 1\n---\nx\n", Set("n", 1e20))
    assert after == "---\nn: 1.0e+20\n---\nx\n"
    assert yaml.safe_load(after.split("---")[1]) == {"n": 1e20}


def test_an_index_out_of_range_says_so():
    with pytest.raises(OperationRefusedError) as raised:
        run(SHAPES["doc-legacy-links"], Set("links[5].x", 1))
    assert "out of range" in raised.value.reason


@pytest.mark.parametrize("path", ["a..b", "", ".a", "a.", "a[x]", "a[0", "a]b", "[0].a"])
def test_a_path_that_cannot_be_read_is_refused(path):
    with pytest.raises(OperationRefusedError):
        run("---\na: {b: 1}\n---\nx\n", Set(path, 2))


def test_limit_a_folded_value_with_an_indented_line_is_written_literal():
    before = "---\ns: >\n  a\nz: 1\n---\nx\n"
    after = _apply1(before, Set("s", "a\n  indented\n"))
    assert after.startswith("---\ns: |\n")
    assert _reader(after)[0]["s"] == "a\n  indented\n"


def test_limit_keep_chomping_on_a_clip_scalar_is_written_double_quoted():
    before = "---\ns: |\n  a\n\nz: 1\n---\nx\n"
    after = _apply1(before, Set("s", "a\n\n"))
    assert '\ns: "a\\n\\n"\n' in after


def test_limit_a_list_written_directly_in_a_list_item_is_refused():
    with pytest.raises(OperationRefusedError):
        run("---\nl:\n- - a\n  - b\n- c\n---\nx\n", Unset("l[0]"))


# --- nothing but OperationRefusedError escapes --------------------------------

# a tagged key in each place a mapping can sit (#749)
TAGGED_KEY_TEXTS = [
    "---\n!foo a: 1\ntags: [a]\n---\nx\n",
    "---\n!!str x: a\ntags: [a]\n---\nx\n",
    "---\n!!str 1: a\ntags: [a]\n---\nx\n",
    "---\nparams:\n  !foo k: 1\n  a: 2\ntags: [a]\n---\nx\n",
    "---\nl:\n- !foo k: a\n  z: 1\ntags: [a]\n---\nx\n",
    "---\nparams: {!foo k: 1, a: 2}\ntags: [a]\n---\nx\n",
]


def test_malformed_operations_raise_only_operation_refused():
    """Fuzz: paths, values and operations built from awkward pieces, on every
    shape. Each call returns, or raises OperationRefusedError with a reason."""
    import random

    rng = random.Random(732)
    parts = [
        "",
        ".",
        "..",
        "[",
        "]",
        "[0]",
        "[-1]",
        "[99]",
        "[x]",
        "a",
        "tags",
        "links",
        "params",
        "0",
        "true",
        "null",
        " ",
        "a.b",
        "#",
        ":",
        "-",
        "'q'",
        " ",
    ]
    odd = [1.5, None, True, (), [], -1, 0, "", "x", object(), b"bytes", {"k": "v"}]
    values = [
        None,
        1,
        "s",
        [1],
        {"a": 1},
        {1, 2},
        float("nan"),
        float("inf"),
        object(),
        {(1, 2): "k"},
        {"k": object()},
        b"x",
        date(2020, 1, 1),
        [[[]]],
        {"": ""},
        {"caf\u00e9": 1, "cafe\u0301": 2},
        {float("nan"): 1},
        [float("nan")],
    ]

    def path():
        if rng.random() < 0.25:
            return tuple(rng.choice(odd + parts) for _ in range(rng.randint(0, 3)))
        return "".join(rng.choice(parts) for _ in range(rng.randint(0, 4)))

    def op():
        kind = rng.randrange(8)
        if kind == 0:
            return Set(path(), rng.choice(values))
        if kind == 1:
            return Append(path(), rng.choice(values))
        if kind == 2:
            return Remove(path(), rng.choice(values))
        if kind == 3:
            return Unset(path())
        if kind == 4:
            return AddSubkey(path(), rng.choice(odd + parts), rng.choice(values))
        if kind == 5:
            return ReplaceBody(rng.choice(["x", "", None, 3, "---\na: 1\n---"]))
        if kind == 6:
            return rng.choice(odd)
        return Set(
            rng.choice(["title", "tags", "links[0].relation", "params.social"]), rng.choice(values)
        )

    reasons: list[str] = []
    texts = [
        *SHAPES.values(),
        COMMENTED,
        "---\na: 1\n? [x, y]\n: v\n---\nx\n",
        "---\np:\n  ? {x: 1}\n  : v\n---\nx\n",
        "---\na: !custom 1\nb: !!set {x}\nc: !!binary aGk=\n---\nx\n",
        "---\ntrue: 1\nnull: 2\n3: c\n---\nx\n",
        "---\nl:\n- - a\n  - b\n---\nx\n",
        # #749: tagged keys, complex keys, .nan and Unicode normalisations
        *TAGGED_KEY_TEXTS,
        "---\na: .nan\ntags: [a, .nan]\n---\nx\n",
        "---\np:\n  .nan: a\n  b: 1\nk: 2\n---\nx\n",
        "---\ncafe\u0301: 1\ncaf\u00e9: 2\ntags: [a]\n---\nx\n",
        "---\np:\n  cafe\u0301: a\ntags: [a]\n---\nx\n",
        "---\n? [x, y]\n: v\np:\n  ? {k: 1}\n  : v\n---\nx\n",
        "---\nl:\n- !tagged {target: t2}\n- target: t1  # tgt\n  # rel\n  relation: r1\n---\nx\n",
    ]
    for _ in range(6000):
        text = rng.choice(texts)
        ops = [op() for _ in range(rng.randint(1, 3))]
        try:
            result = apply(text, ops, span_of(text))
        except OperationRefusedError as e:
            reasons.append(e.reason)
            continue
        assert isinstance(result[0], str)
    assert all(reasons), "a refusal without a reason"


# --- budget -------------------------------------------------------------------


def test_budget_many_operations_and_a_long_list():
    """Generous ceilings (measured 0.4 s and 0.1 s on a laptop, round 1; were
    30 s and 3.2 s): one parse per batch of distinct keys, a list compared
    by its common head and tail before any LCS."""
    import time

    text = "---\n" + "".join(f"k{i}: v{i}\n" for i in range(500)) + "---\nx\n"
    started = time.perf_counter()
    apply(text, [Set(f"k{i}", "w") for i in range(500)], span_of(text))
    assert time.perf_counter() - started < 5

    items = [f"item-{i}" for i in range(2000)]
    text = "---\ntags:\n" + "".join(f"- {x}\n" for x in items) + "---\nx\n"
    new = items[:]
    new[1000] = "changed"
    started = time.perf_counter()
    apply(text, [Set("tags", new)], span_of(text))
    assert time.perf_counter() - started < 5


# --- the sweep: every shape, every key, through the byte oracle ---------------

_SWEEP_VALUES = [
    "new value",
    "yes",
    "123",
    "a: b",
    "",
    " lead",
    "2026-05-05",
    7,
    2.5,
    True,
    None,
    ["a", "b"],
    {"k": "v", "n": {"m": 1}},
    [],
    {},
    "multi\nline\n",
]


def _sweep_ops(meta: dict) -> list:
    ops: list = [Set("brand_new", {"a": [1, {"b": 2}]}), Set(("x", "y", "z"), "deep")]
    for k, v in meta.items():
        ops.append(Unset(k))
        ops += [Set(k, value) for value in _SWEEP_VALUES]
        if isinstance(v, list) or v is None:
            ops.append(Append(k, "zz"))
        if isinstance(v, list) and v:
            ops += [
                Append(k, {"target": "t", "relation": "r"}),
                Remove(k, v[0]),
                Remove(k, v[-1]),
                Unset((k, 0)),
                Set(k, list(reversed(v))),
                Set(k, v + v),
                Set(k, v[1:] + ["new"]),
            ]
            if isinstance(v[0], dict):
                for sub in v[0]:
                    ops += [Unset((k, 0, sub)), Set((k, 0, sub), "changed")]
                ops.append(AddSubkey((k, 0), "brandnew", "x"))
        if isinstance(v, dict):
            for sub in v:
                ops += [Unset((k, sub)), Set((k, sub), "c"), Set((k, sub), {"deep": [1, 2]})]
            ops.append(Set((k, "added"), [1]))
    return ops


# Comments in every place a frontmatter can hold one (the cold read's p6 file,
# extended): a header, a key line, after an inline value, between items, on a
# dash line, between a dash-line pair and its sibling, deep in a nested map,
# on a block scalar's header, between keys, after the last key.
COMMENTED = (
    "---\n"
    "# head\n"
    "id: x   # the id\n"
    "tags: # tag list\n"
    "  - a  # first\n"
    "  # between\n"
    "  - b\n"
    "# before links\n"
    "links:\n"
    "- target: t1  # tgt\n"
    "  # rel note\n"
    "  relation: r1\n"
    "- target: t2\n"
    "  relation: r2\n"
    "  extra:\n"
    "    k: v # deep\n"
    "# before params\n"
    "params:\n"
    "  x: 1 # px\n"
    "  # middle\n"
    "  y: 2\n"
    "  z:\n"
    "  - q\n"
    "flow: [a, b]  # f\n"
    "notes: |  # literal\n"
    "  one\n"
    "  two\n"
    "\n"
    "empty:\n"
    "n: ~\n"
    "# tail\n"
    "---\n"
    "body\n"
)


@pytest.mark.parametrize("variant", ["lf", "crlf", "bom"])
def test_sweep_every_shape_through_the_byte_oracle(variant):
    """Every key of every shape, set to awkward values, unset, appended to,
    removed from: each result passes ``check_contract`` (the byte oracle and
    the reader), or is refused with a reason. None may be refused here: these
    are all edits the module supports."""
    refused = []
    for name, text in {**SHAPES, "commented": COMMENTED}.items():
        if name in ("anchor-alias", "duplicate-keys"):
            continue
        if variant == "crlf":
            text = text.replace("\r\n", "\n").replace("\n", "\r\n")
        elif variant == "bom" and not text.startswith("﻿"):
            text = "﻿" + text
        for op in _sweep_ops(_reader(text)[0]):
            try:
                after, report = run(text, op)
            except OperationRefusedError as e:
                refused.append((name, op, e.reason))
                continue
            # every sweep edit has a narrow form: none may widen (round 2)
            assert report.widened == (), (name, op)
            if after is not text:
                check_contract(text, [op], after)
    assert not refused, refused[:5]


# --- round 2 (#732): narrow wherever a narrow edit can express it -------------


@pytest.mark.parametrize(
    "keys", [("x", "y"), ("alpha", "beta"), ("".join(["al", "pha"]), "be" + "ta")]
)
def test_a_map_set_with_long_keys_stays_narrow(keys):
    """Keys longer than one character are not interned: comparing them by
    identity made every kept key look new, and the edit widened (B1)."""
    a, b = keys
    before = f"---\np:\n  {a}: 1  # keep\n  # between\n  {b}: 2\nz: 1\n---\nb\n"
    after, report = run(before, Set("p", {a: 1, b: 3}))
    assert report.widened == ()
    assert after == before.replace(f"{b}: 2", f"{b}: 3")


def test_a_nested_map_set_map_to_map_keeps_comments_between_pairs():
    before = (
        "---\np:\n  # about q\n  q:\n    alpha: 1  # a\n    # mid\n    beta: 2\n"
        "  # after q\n  r: 1\n---\nx\n"
    )
    after, report = run(before, Set("p.q", {"alpha": 1, "beta": 3, "gamma": 4}))
    assert report.widened == ()
    assert after == before.replace("    beta: 2\n", "    beta: 2\n    gamma: 4\n").replace(
        "beta: 2", "beta: 3"
    )


def test_a_hugo_params_set_changing_one_value_keeps_its_comments():
    before = (
        "---\ntitle: T\nparams:\n    author: Jane\n    # social block\n    social:\n"
        "        twitter: jane\n    draft: false\n---\nx\n"
    )
    new = {"author": "Jane", "social": {"twitter": "jane"}, "draft": True}
    after, report = run(before, Set("params", new))
    assert report.widened == ()
    assert after == before.replace("draft: false", "draft: true")


def test_an_item_map_set_keeps_its_comments():
    before = (
        "---\nlinks:\n- target: t1  # tgt\n  # rel note\n  relation: r1\n- target: t2\n---\nx\n"
    )
    after, report = run(before, Set("links[0]", {"target": "t1", "relation": "r2"}))
    assert report.widened == ()
    assert after == before.replace("relation: r1", "relation: r2")


def test_a_whole_list_set_keeps_the_comments_between_kept_items():
    """Decision 2: every existing item's bytes stay, and so do the lines
    between them."""
    before = (
        "---\nlinks:\n- target: t1  # first link\n  relation: r1\n# between 0 and 1\n"
        "- target: t2\n  relation: r2\n- target: t3\n  relation: r3\nz: 1\n---\nx\n"
    )
    cur = [{"target": f"t{i}", "relation": f"r{i}"} for i in (1, 2, 3)]
    changed = [dict(x) for x in cur]
    changed[2]["relation"] = "CHANGED"
    after, report = run(before, Set("links", changed))
    assert report.widened == ()
    assert after == before.replace("relation: r3", "relation: CHANGED")
    after, report = run(before, Set("links", [*cur[:2], {"target": "t9"}]))
    assert report.widened == ()
    assert "# between 0 and 1\n" in after and "  relation: r2\n" in after


def _fault(monkeypatch, target: str, replacement: str):
    from pyrite.storage import file_operations as fo

    real = fo._narrow_edits

    def corrupt(doc, op):
        at = doc.text.index(target)
        return [*real(doc, op), (at, at + len(target), replacement)]

    monkeypatch.setattr(fo, "_narrow_edits", corrupt)


def test_the_widen_of_a_map_keeps_the_files_order_and_its_comments(monkeypatch):
    """Decision 2: a widen copies each unchanged pair's bytes and the lines
    between pairs, in the file's order; only the changed pair is emitted."""
    before = "---\nparams:\n  b: 1  # bee\n  # about a\n  a: 2\n  c: 3\nz: x  # zed\n---\nx\n"
    _fault(monkeypatch, "# zed", "# ZED")
    after, report = run(before, Set("params", {"a": 2, "b": 1, "c": 4}))
    assert report.widened == ("params",)
    assert after == before.replace("c: 3", "c: 4")


def test_the_widen_of_a_list_keeps_the_comments_between_kept_items(monkeypatch):
    before = "---\ntags:\n- a  # A\n# about b\n- b\n- c\nz: x  # zed\n---\nx\n"
    _fault(monkeypatch, "# zed", "# ZED")
    after, report = run(before, Set("tags", ["a", "b", "X", "d"]))
    assert report.widened == ("tags",)
    assert after == before.replace("- c\n", "- X\n- d\n")


@pytest.mark.parametrize(
    "complex_key", ["? [x, y]\n: v\n", "? {x: 1}\n: v\n", "p:\n  ? [x]\n  : v\n"]
)
def test_a_complex_key_anywhere_is_refused_with_a_reason(complex_key):
    text = f"---\na: 1\n{complex_key}---\nx\n"
    with pytest.raises(OperationRefusedError) as raised:
        run(text, Set("a", 2))
    assert "complex key" in raised.value.reason


@pytest.mark.parametrize("tagged", ["!custom 1", "!!set {x, y}", "!!binary aGk=", "!!omap [x: 1]"])
def test_a_tagged_value_elsewhere_does_not_block_an_edit(tagged):
    """L4: an untouched tagged value compares equal to itself after the reparse."""
    text = f"---\na: {tagged}\nb: 1\n---\nx\n"
    assert _apply1(text, Set("b", 2)) == text.replace("b: 1", "b: 2")


@pytest.mark.parametrize(
    ("ops", "expected"),
    [
        ([Unset("tags[0]"), Unset("tags[0]")], "tags: []\n"),
        ([Unset("title"), Set("title", "U")], "tags:\n- a\n- b\ntitle: U\n"),
        ([Append("tags", "c"), Remove("tags", "a")], "tags:\n- b\n- c\n"),
    ],
)
def test_a_same_key_sequence_in_one_call(ops, expected):
    """L1: each operation is checked against the text it applied to, not the
    call's original."""
    before = "---\ntitle: T\ntags:\n- a\n- b\n---\nx\n"
    after = _apply1(before, *ops)
    assert after.endswith(expected + "---\nx\n")


def test_a_shared_value_in_one_call_does_not_alias_in_the_model():
    """L2: [d, d] set, then one item changed: only that item changes."""
    d = {"a": 1}
    after = _apply1("---\nl:\n- {a: 1}\n---\nx\n", Set("l", [d, d]), Set("l[0].a", 2))
    assert _reader(after)[0]["l"] == [{"a": 2}, {"a": 1}]


def test_limit_a_batch_indents_new_lines_by_the_conventions_before_it():
    """L3, pinned: operations on different keys in one call are spliced
    against one parse, so a list emitted in the same call that removes the
    file's only indented list still uses that list's indent; one by one, the
    second call no longer sees it."""
    before = "---\ntags:\n  - a\nid: x\n---\nb\n"
    together = _apply1(before, Set("tags", 7), Set("id", ["p"]))
    one, _ = run(before, Set("tags", 7))
    one = _apply1(one, Set("id", ["p"]))
    assert together == "---\ntags: 7\nid:\n  - p\n---\nb\n"
    assert one == "---\ntags: 7\nid:\n- p\n---\nb\n"
    assert _reader(together)[0] == _reader(one)[0]


@pytest.mark.parametrize("key", ["---", "...", "--- x"])
def test_a_new_key_spelled_like_a_document_marker_is_quoted(key):
    """L5: Pyrite is a guest in files other tools split on ``---``."""
    after = _apply1("---\nk: v\n---\nb\n", Set((key,), 1))
    assert f'\n"{key}": 1\n' in after


def test_limit_unset_of_a_dash_line_pair_before_a_comment_leaves_the_dash_alone():
    """L6, pinned (cosmetic): the comment line's bytes are outside the
    unset's span, so the dash stays on its line before it."""
    before = "---\nl:\n- target: a\n  # note\n  relation: b\n---\nx\n"
    assert _apply1(before, Unset("l[0].target")) == "---\nl:\n-   # note\n  relation: b\n---\nx\n"


@pytest.mark.parametrize(
    "text",
    [
        "---\np:\n  a: 1\n  s: |\n    text\n    # not a comment\nz: 1\n---\nx\n",
        '---\np:\n  a: "x\n    # inside quotes"\nz: 1\n---\nx\n',
    ],
    ids=["literal", "double-quoted"],
)
def test_limit_a_comment_looking_last_line_refuses_an_insertion_after_it(text):
    with pytest.raises(OperationRefusedError):
        run(text, Set("p.new", 1))
    # an edit that does not insert after that line is not affected
    assert _apply1(text, Unset("z")).endswith("---\nx\n")


def test_the_widen_of_a_nested_operation_rebuilds_its_top_level_value(monkeypatch):
    """Decision 2: a widen goes to the whole top-level value, so a nested
    operation whose narrow edit fails is checked against that value's span."""
    before = "---\nparams:\n  b: 1  # bee\n  # about c\n  c: 3  # cee\nz: x  # zed\n---\nx\n"
    _fault(monkeypatch, "# zed", "# ZED")
    after, report = run(before, Set("params.c", 4))
    assert report.widened == ("params",)
    # the changed pair is emitted afresh (its own comment goes with it); the
    # kept pair, the comment between them and every byte outside stay
    assert after == before.replace("c: 3  # cee", "c: 4")


# --- round 3 (#749): what Pyrite cannot edit narrowly is refused, truthfully ---
#
# The reference is ruamel's round-trip loader (what ``load_yaml`` uses): each
# input below records what it loads, then asserts that ``apply`` edits
# narrowly or refuses with a reason that matches (Andon #745).

_EVERY_OP = [
    Set("tags", ["z"]),
    Set("brand_new", 1),
    Set("params.k", 2),
    Append("tags", "z"),
    Remove("tags", "a"),
    Unset("tags"),
    AddSubkey("params", "z", 1),
    ReplaceBody("new body"),
]


def _ruamel_keys(text: str) -> list:
    from pyrite.utils.yaml import load_yaml

    span = span_of(text)
    keys: list = []

    def walk(node: Any) -> None:
        if isinstance(node, dict):
            for k, v in node.items():
                keys.append(k)
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    walk(load_yaml(text[span.start : span.end]))
    return keys


@pytest.mark.parametrize("text", TAGGED_KEY_TEXTS)
def test_a_tagged_key_anywhere_is_refused_with_its_reason(text):
    """Reference: ruamel loads a tagged key as a ``TaggedScalar``, a value that
    no path can name and Python cannot hash as the string it looks like. Today
    every operation raised ``TypeError`` or ``KeyError``."""
    assert any(type(k).__name__ == "TaggedScalar" for k in _ruamel_keys(text))
    for op in _EVERY_OP:
        with pytest.raises(OperationRefusedError) as raised:
            run(text, op)
        assert "tagged key" in raised.value.reason, op


def test_a_tagged_key_whose_loaded_type_differs_from_its_plain_reading_is_refused():
    """``!!float 1: a``: ruamel loads the key as the float 1.0 (not a
    TaggedScalar), while the same key written plain reads as the int 1. Path
    ``1`` would name the wrong thing (today: ``KeyError``). Guard: a key
    node's explicit tag against what it resolves to written plain."""
    text = "---\n!!float 1: a\ntags: [a]\n---\nx\n"
    keys = _ruamel_keys(text)
    assert type(keys[0]).__name__ == "ScalarFloat" and keys[0] == 1.0
    for op in [Set("tags", ["z"]), Set("1", "q")]:
        with pytest.raises(OperationRefusedError) as raised:
            run(text, op)
        assert "tagged key" in raised.value.reason


@pytest.mark.control(reason="a tagged value or a quoted key was already editable; pins it stays so")
def test_a_tagged_value_and_a_quoted_or_anchored_plain_key_are_still_editable():
    """Control: only a *key's* explicit tag is refused; quoting a key, a tag on
    a value and a tag spelled as text are edited as before."""
    for text in [
        '---\n"!foo": 1\ntags: [a]\n---\nx\n',
        "---\nk: !foo 1\ntags: [a]\n---\nx\n",
        "---\n'!!str': 1\ntags: [a]\n---\nx\n",
    ]:
        after, _ = run(text, Set("tags", ["z"]))
        assert after == text.replace("[a]", "[z]")


@pytest.mark.control(reason="a new key spelled like a tag was already quoted; pins it stays so")
@pytest.mark.parametrize("key", ["!foo", "!!str", "!!int 1", "&a", "*a"])
def test_a_new_key_spelled_like_a_tag_is_written_so_it_reads_back_as_a_string(key):
    text = "---\ntags: [a]\n---\nx\n"
    after, _ = run(text, Set((key,), 1))
    assert _reader(after)[0][key] == 1


@pytest.mark.parametrize(
    "text",
    [
        "---\nn: .nan\nb: 1\n---\nx\n",
        "---\nn: [1, .nan]\nb: 1\n---\nx\n",
        "---\nn: {x: .nan}\nb: 1\n---\nx\n",
        "---\np:\n  .nan: a\nb: 1\n---\nx\n",
        "---\n.nan: a\nb: 1\n---\nx\n",
        pytest.param(
            "---\nn: !foo .nan\nb: 1\n---\nx\n",
            marks=pytest.mark.control(reason="a tagged NaN already compared equal to itself"),
        ),
        pytest.param(
            "---\nn: !!set {.nan}\nb: 1\n---\nx\n",
            marks=pytest.mark.control(reason="a set holding NaN already compared equal"),
        ),
    ],
    ids=["value", "in-list", "in-flow-map", "nested-key", "top-key", "tagged-value", "in-set"],
)
def test_a_nan_anywhere_does_not_block_an_edit_of_another_key(text):
    """Reference: ruamel loads ``.nan`` as a float that is never equal to
    itself. Choice (#749): NaN equals NaN, so a file holding one stays
    editable and an untouched NaN compares equal after the reparse. Today every
    edit was refused ('does not parse to the operation applied')."""
    after, report = run(text, Set("b", 2))
    assert after == text.replace("b: 1", "b: 2")
    assert report.widened == ()
    if "!foo" not in text:  # the oracle compares loaded TaggedScalars by identity
        check_contract(text, [Set("b", 2)], after)


def test_a_nan_value_set_to_nan_is_unchanged_and_one_can_be_added_or_removed():
    text = "---\nn: .nan\nl: [1, .nan, 2]\n---\nx\n"
    same, report = run(text, Set("n", float("nan")), Set("l", [1, float("nan"), 2]))
    assert same == text and not report.changed
    after, _ = run(text, Remove("l", float("nan")))
    assert after == text.replace("[1, .nan, 2]", "[1, 2]")
    after, _ = run(text, Append("l", float("nan")))
    assert _reader(after)[0]["l"][-1] != _reader(after)[0]["l"][-1]  # a NaN went in
    after, _ = run(text, Set("n", 1.5))
    assert after == text.replace("n: .nan", "n: 1.5")


def test_a_nan_key_is_named_by_its_segment_and_kept_by_a_map_set():
    """Keys: ``('p', '.nan')`` reads as the float key; a whole-map set that
    keeps the NaN key leaves its pair alone."""
    text = "---\np:\n  .nan: a  # n\n  b: 1\n---\nx\n"
    after, _ = run(text, Set(("p", ".nan"), "q"))
    assert after == text.replace("a  # n", "q  # n")
    after, report = run(text, Set("p", {float("nan"): "a", "b": 2}))
    assert after == text.replace("b: 1", "b: 2") and report.widened == ()


_NFD = "cafe\u0301"
_NFC = "caf\u00e9"


def test_a_key_in_another_unicode_normalisation_is_refused_not_added_beside_it():
    """Reference: ruamel keeps the NFD bytes, so ``load_yaml`` returns a key
    that is not equal to the NFC string. Choice (#749): do not normalise (the
    file's spelling is the user's, and a rewrite would change it); refuse a
    path or a new sub-key that differs from an existing key only by
    normalisation. Today a second, identical-looking key was added."""
    text = f"---\np:\n  {_NFD}: a\ntags: [a]\n---\nx\n"
    assert _ruamel_keys(text)[1] == _NFD != _NFC
    for op in [
        Set(f"p.{_NFC}", "q"),
        Unset(f"p.{_NFC}"),
        AddSubkey("p", _NFC, "q"),
        Set(("p", _NFC, "deeper"), 1),
    ]:
        with pytest.raises(OperationRefusedError) as raised:
            run(text, op)
        assert "normalisation" in raised.value.reason, op
    top = f"---\n{_NFD}: a\n---\nx\n"
    with pytest.raises(OperationRefusedError):
        run(top, Set(_NFC, "q"))


@pytest.mark.control(
    reason="the file's own spelling was already editable; the refusal must not reach it"
)
def test_the_files_own_spelling_and_a_file_holding_both_spellings_are_editable():
    """Control: the NFD path names the NFD key; with both spellings in the file
    each path names its own (neither is ambiguous), and a whole-map set that
    changes the spelling is exactly what was asked."""
    text = f"---\np:\n  {_NFD}: a\ntags: [a]\n---\nx\n"
    after, _ = run(text, Set(f"p.{_NFD}", "q"))
    assert after == text.replace(": a", ": q")
    both = f"---\n{_NFD}: 1\n{_NFC}: 2\n---\nx\n"
    after, _ = run(both, Set(_NFC, 9))
    assert after == f"---\n{_NFD}: 1\n{_NFC}: 9\n---\nx\n"
    after, _ = run(text, Set("p", {_NFC: "a"}))
    assert _reader(after)[0]["p"] == {_NFC: "a"}


@pytest.mark.control(reason="pins that unsetting a list's last item keeps the comment lines")
@pytest.mark.parametrize(
    ("before", "path", "after"),
    [
        ("l:\n- a\n# c1\n- b\n# c2\n- c\nz: 1\n", "l[2]", "l:\n- a\n# c1\n- b\n# c2\nz: 1\n"),
        (
            "p:\n  l:\n    - a\n    # c1\n    - b\n    # c2\n    - c\n    # c3\n  s: 1\n",
            "p.l[-1]",
            "p:\n  l:\n    - a\n    # c1\n    - b\n    # c2\n    # c3\n  s: 1\n",
        ),
        (
            "l:\n- t: a\n  # in\n  u: 1\n# c1\n- t: b\n# c2\n- t: c\n  u: 2\nz: 1\n",
            "l[2]",
            "l:\n- t: a\n  # in\n  u: 1\n# c1\n- t: b\n# c2\nz: 1\n",
        ),
    ],
    ids=["block", "indented-with-tail", "mapping-items"],
)
def test_unsetting_a_lists_last_item_keeps_the_comment_lines_between_its_items(before, path, after):
    """#749 item 5 said the comment lines were dropped. Not reproduced on
    ~16000 generated layouts (see the PR); pinned so it stays so."""
    text = f"---\n{before}---\nx\n"
    got, report = run(text, Unset(path))
    assert got == f"---\n{after}---\nx\n" and report.widened == ()
    check_contract(text, [Unset(path)], got)
