"""Pin SDK-published MCP input schemas and fixed valid argument examples (#609).

These examples validate the wire contract, not handler semantics or live KB data.
Core always runs; the explicit in-tree profile requires the six shipped plugins.
Snapshots are reviewed files and are never regenerated by pytest.
"""

import asyncio
import importlib
import json
from pathlib import Path
import pytest
from jsonschema import validators
from mcp.types import ListToolsRequest
from pyrite.config import PyriteConfig, Settings
from pyrite.plugins.registry import PluginRegistry
from pyrite.server.mcp_server import PyriteMCPServer

GOLDENS = Path(__file__).parent / "characterization" / "goldens"
PLUGINS = {
    "pyrite_zettelkasten.plugin": "ZettelkastenPlugin",
    "pyrite_software_kb.plugin": "SoftwareKBPlugin",
    "pyrite_journalism_investigation.plugin": "JournalismInvestigationPlugin",
    "pyrite_encyclopedia.plugin": "EncyclopediaPlugin",
    "pyrite_cascade.plugin": "CascadePlugin",
    "pyrite_social.plugin": "SocialPlugin",
}


def schema_registry(profile):
    registry = PluginRegistry()
    if profile == "in-tree":
        for module, cls in PLUGINS.items():
            registry.register(getattr(pytest.importorskip(module), cls)())
    return registry


def published_schemas(root, tier, registry, monkeypatch):
    monkeypatch.setattr("pyrite.plugins.get_registry", lambda: registry)
    monkeypatch.setattr("pyrite.plugins.registry.get_registry", lambda: registry)
    config = PyriteConfig(
        knowledge_bases=[], settings=Settings(index_path=root / (tier + ".db"), auto_embed=False)
    )
    server = PyriteMCPServer(config, tier=tier)
    try:
        sdk = server.build_sdk_server()
        result = asyncio.run(
            sdk.request_handlers[ListToolsRequest](ListToolsRequest(method="tools/list"))
        )
        tools = result.root.tools
        assert tools
        return {tool.name: tool.inputSchema for tool in sorted(tools, key=lambda t: t.name)}
    finally:
        server.db.close()


@pytest.fixture(params=["core", "in-tree"])
def profile(request):
    return request.param


@pytest.mark.parametrize("tier", ["read", "write", "admin"])
def test_sdk_published_input_schemas_are_pinned(profile, tier, tmp_path, monkeypatch):
    expected = json.loads(
        (GOLDENS / f"mcp-input-schemas.{profile}.json").read_text(encoding="utf-8")
    )
    actual = published_schemas(tmp_path, tier, schema_registry(profile), monkeypatch)
    assert actual == {name: item["inputSchema"] for name, item in expected[tier].items()}


@pytest.mark.parametrize("tier", ["read", "write", "admin"])
def test_fixed_known_good_arguments_validate_for_every_published_tool(
    profile, tier, tmp_path, monkeypatch
):
    examples = json.loads(
        (GOLDENS / f"mcp-input-schemas.{profile}.json").read_text(encoding="utf-8")
    )[tier]
    schemas = published_schemas(tmp_path, tier, schema_registry(profile), monkeypatch)
    assert schemas.keys() == examples.keys()
    for name, schema in schemas.items():
        validator = validators.validator_for(schema)
        validator.check_schema(schema)
        validator(schema).validate(examples[name]["arguments"])
