"""``apply(text, ops, span)``: operations on an entry file's text (ADR-0042 P1).

ADR-0042 decisions 1, 2, 3 and 6, amendment A4; #730 section 1 and phase P1.
The function is pure and not wired to any write path yet (P3 does that).

The fixtures are the 17 hand-made shapes of #730 section 1, written here by
hand as string literals, never generated by Pyrite. They are string literals
rather than files because several shapes are bytes the repo's pre-commit hooks
would "fix" in a file: CRLF, a BOM, trailing spaces, a body with no final
newline.

The oracle is independent of the module under test:

- the reader parses before and after (``_frontmatter_of``, the split every read
  uses);
- the expected value is the operations applied to the parsed dict by
  ``_expected`` below;
- a top-level key's own lines are found by a line scan (``_key_blocks``), not by
  the module's composer spans;
- equality is ``_eq``, ADR-0042 decision 3 written out again here.

Each guard the module adds has a test that fails when that guard alone is
removed. They are listed in the PR.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any

import pytest

from pyrite.exceptions import FrontmatterError
from pyrite.models.core_types import _frontmatter_of
from pyrite.storage.file_operations import (
    AddSubkey,
    Append,
    FrontmatterSpan,
    OperationRefusedError,
    Remove,
    ReplaceBody,
    Set,
    Unset,
    apply,
    values_equal,
)

# --- the 17 shapes (#730 section 1) -----------------------------------------

SHAPES: dict[str, str] = {
    # 1. the doc's first example (docs/how-pyrite-edits-your-files.md)
    "doc-field-notes": (
        "---\n"
        "# reviewed by hand, do not reorder\n"
        "id: field-notes\n"
        "title: Field notes   # working title\n"
        "type: note\n"
        "\n"
        "tags: [alpha, beta]\n"
        "links:\n"
        "- target: other-entry\n"
        "  relation: related\n"
        "flag: no\n"
        "---\n"
        "\n"
        "    an indented first line\n"
        "\n"
        "Text.\n"
    ),
    # 2. the doc's second example: a hand-written link in a legacy spelling
    "doc-legacy-links": (
        "---\n"
        "id: legacy-links\n"
        "title: Legacy links\n"
        "type: note\n"
        "links:\n"
        "- to: foo          # legacy spelling, hand written\n"
        "  type: related\n"
        "  since: 2020\n"
        "---\n"
        "\n"
        "Text.\n"
    ),
    # 3. CRLF line endings
    "crlf": (
        "---\r\n"
        "# header comment\r\n"
        "id: echo-me\r\n"
        'title: "Quoted title"\r\n'
        "type: note\r\n"
        "date: 2026-01-15\r\n"
        "tags: [alpha, beta]  # trailing\r\n"
        "---\r\n"
        "\r\n"
        "Body.\r\n"
    ),
    # 4. a byte-order mark
    "bom": ("﻿---\nid: bom\ntitle: With a BOM\ntags:\n- a\n- b\n---\n\nText.\n"),
    # 5. a single-quoted scalar with an escaped quote and a '#', and a comment
    "quoted": (
        "---\n"
        "id: quoted\n"
        "title: 'it''s the #1 hit'   # c\n"
        'summary: "say \\"hi\\""\n'
        "---\n"
        "\n"
        "Text.\n"
    ),
    # 6. bare words a YAML 1.1 reader would misread; Pyrite reads YAML 1.2
    "yaml11-words": (
        "---\nid: words\nflag: no\nother: yes\nnil: null\nstatus: draft\n---\n\nText.\n"
    ),
    # 7. block scalars: folded, then literal, then a plain key
    "block-scalars": (
        "---\n"
        "id: folded\n"
        "summary: >\n"
        "  a folded\n"
        "  paragraph\n"
        "\n"
        "notes: |\n"
        "  line one\n"
        "  line two\n"
        "next: 1\n"
        "---\n"
        "\n"
        "Text.\n"
    ),
    # 8. a plain scalar that runs over two lines
    "multiline-plain": (
        "---\nid: multi\ntitle: a plain scalar\n  that wraps\nother: x\n---\n\nText.\n"
    ),
    # 9. a zero-indent list next to an indented list
    "mixed-list-indent": (
        "---\nid: mixed\ntags:\n- a\n- b\naliases:\n  - x\n  - y\n---\n\nText.\n"
    ),
    # 10. an anchor, an alias and a merge key
    "anchor-alias": (
        "---\n"
        "id: anchored\n"
        "base: &b\n"
        "  k: v\n"
        "child: *b\n"
        "merged:\n"
        "  <<: *b\n"
        "  own: 1\n"
        "plain: ok\n"
        "---\n"
        "\n"
        "Text.\n"
    ),
    # 11. duplicate keys
    "duplicate-keys": ("---\nid: dup\ntitle: one\ntitle: two\nstatus: draft\n---\n\nText.\n"),
    # 12. a Hugo post: 4-space nested map, RFC 3339 date, shortcode body, no id
    "hugo": (
        "---\n"
        'title: "My first post"\n'
        "date: 2024-03-01T09:30:00-05:00\n"
        "draft: false\n"
        "params:\n"
        "    author: Jane\n"
        "    social:\n"
        "        twitter: jane\n"
        'tags: ["hugo", "notes"]\n'
        "---\n"
        "\n"
        '{{< figure src="/img/a.png" caption="A" >}}\n'
        "\n"
        "Body text.\n"
    ),
    # 13. a comment above a key that gets unset
    "comment-above-unset": (
        "---\n"
        "id: commented\n"
        "title: T\n"
        "# the next key is deprecated\n"
        "legacy: old\n"
        "status: draft\n"
        "---\n"
        "\n"
        "Text.\n"
    ),
    # 14. a body with no trailing newline
    "no-final-newline": "---\nid: nonl\ntitle: T\n---\n\nText without a newline",
    # 15. odd spacing: wide gap after a key, trailing spaces, a 4-space list
    "odd-spacing": (
        "---\nid:    odd\ntitle: Trailing space   \ntags:\n    - one\n    - two\n---\n\nText.\n"
    ),
    # 16. an empty flow list and an empty flow map
    "empty-flow": "---\nid: empty\ntags: []\nlinks: {}\n---\n\nText.\n",
    # 17. a date, and a date written as a quoted string
    "dates": ("---\nid: dated\ndate: 2026-01-15\nupdated: '2026-01-16'\n---\n\nText.\n"),
}


# --- the test's own frontmatter span, checked against the reader ------------


def span_of(text: str) -> FrontmatterSpan | None:
    """Where ``text``'s YAML frontmatter is: the caller's job in production
    (the one-frontmatter-splitter theme will own it). Checked against the
    reader's split so this helper cannot drift from it unnoticed."""
    at = 1 if text.startswith("﻿") else 0
    if not text.startswith("---", at):
        return None
    start = text.index("\n", at) + 1
    pos = start
    while pos < len(text):
        nl = text.find("\n", pos)
        line_end = len(text) if nl == -1 else nl + 1
        if text[pos:line_end].rstrip() == "---":
            span = FrontmatterSpan(start, pos, line_end)
            try:
                parsed = _frontmatter_of(text)
            except FrontmatterError:  # duplicate keys: the reader refuses
                return span
            assert parsed is not None
            assert parsed[1] == text[line_end:].strip()
            return span
        pos = line_end
    return None


def run(text: str, *ops: Any):
    return apply(text, list(ops), span_of(text))


# --- the independent oracle --------------------------------------------------


def _eq(a: Any, b: Any) -> bool:
    """ADR-0042 decision 3, written again from the ADR, for the oracle."""
    if isinstance(a, bool) or isinstance(b, bool):
        return type(a) is bool and type(b) is bool and a == b
    if a is None or b is None:
        return a is None and b is None
    if isinstance(a, int | float) and isinstance(b, int | float):
        return a == b
    if isinstance(a, str) and isinstance(b, date | datetime):
        a, b = b, a
    if isinstance(a, date | datetime) and isinstance(b, str):
        if a.isoformat() == b or (isinstance(a, datetime) and a.isoformat(" ") == b):
            return True
        if isinstance(a, datetime):
            try:
                other = datetime.fromisoformat(b)
            except ValueError:
                return False
            if (a.tzinfo is None) != (other.tzinfo is None):
                return False
            return a == other
        return False
    if isinstance(a, dict) and isinstance(b, dict):
        return set(a) == set(b) and all(_eq(a[k], b[k]) for k in a)
    if isinstance(a, list) and isinstance(b, list):
        return len(a) == len(b) and all(_eq(x, y) for x, y in zip(a, b, strict=True))
    if type(a) is not type(b) and not (isinstance(a, str) and isinstance(b, str)):
        return False
    return a == b


def _plain(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(k): _plain(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_plain(v) for v in value]
    if type(value).__name__ == "ScalarBoolean":
        return bool(value)
    if isinstance(value, datetime) and type(value) is not datetime:
        # ruamel's TimeStamp loses its tzinfo under copy.deepcopy
        return datetime.fromisoformat(value.isoformat())
    return value


def _reader(text: str) -> tuple[dict, str]:
    parsed = _frontmatter_of(text)
    assert parsed is not None, "the reader finds no frontmatter in the result"
    return _plain(dict(parsed[0])), parsed[1]


def _segments(path: Any) -> list:
    if isinstance(path, tuple | list):
        return list(path)
    out: list = []
    for part in path.split("."):
        name, _, rest = part.partition("[")
        if name:
            out.append(name)
        while rest:
            index, _, rest = rest.partition("]")
            out.append(int(index))
            rest = rest[1:] if rest.startswith("[") else rest
    return out


def _expected(meta: dict, op: Any) -> dict:
    """The operation applied to the parsed value, by hand."""
    import copy

    result = copy.deepcopy(meta)
    if isinstance(op, ReplaceBody):
        return result
    segs = _segments(op.path)
    if isinstance(op, AddSubkey):
        segs = [*segs, op.key]
    parent: Any = result
    for seg in segs[:-1]:
        if isinstance(parent, dict) and (seg not in parent or parent[seg] is None):
            if isinstance(op, Unset | Remove):
                return result
            parent[seg] = {}
        parent = parent[seg]
    last = segs[-1]
    if isinstance(op, Set | AddSubkey):
        if isinstance(parent, dict) and last in parent and _eq(parent[last], op.value):
            return result
        parent[last] = op.value
    elif isinstance(op, Unset):
        if isinstance(parent, dict):
            parent.pop(last, None)
        else:
            del parent[last]
    elif isinstance(op, Append):
        if parent.get(last) is None:
            parent[last] = []
        parent[last].append(op.value)
    elif isinstance(op, Remove):
        items = parent.get(last) or []
        for i, item in enumerate(items):
            if _eq(item, op.value):
                del items[i]
                break
    return result


def _key_blocks(text: str) -> dict[str, str]:
    """Each top-level key's own lines, by a line scan: a key line starts at
    column 0 and is not a comment or a list item; its block runs to the next
    key line, less trailing blank and comment-only lines."""
    span = span_of(text)
    assert span is not None
    lines = text[span.start : span.end].splitlines(keepends=True)
    blocks: dict[str, list[str]] = {}
    current = None
    for line in lines:
        head = line[:1]
        if head and head not in " \t#-\r\n" and ":" in line:
            current = line.split(":", 1)[0].strip().strip("'\"")
            blocks[current] = [line]
        elif current is not None:
            blocks[current].append(line)
    out = {}
    for key, block in blocks.items():
        while len(block) > 1 and (not block[-1].strip() or block[-1].lstrip().startswith("#")):
            block = block[:-1]
        out[key] = "".join(block)
    return out


def _top(op: Any) -> str | None:
    if isinstance(op, ReplaceBody):
        return None
    return str(_segments(op.path)[0])


def check_contract(before: str, ops: list, after: str) -> None:
    """Properties 1 and 3 for any result: untouched top-level keys are
    byte-identical; the reader gets exactly the operations applied; key order
    holds with new keys last; prefix (BOM), body and line endings are kept."""
    named = {_top(op) for op in ops}
    old_blocks, new_blocks = _key_blocks(before), _key_blocks(after)
    for key, block in old_blocks.items():
        if key not in named:
            assert new_blocks.get(key) == block, f"untouched key {key!r} changed"
    meta, body = _reader(before)
    expected = meta
    for op in ops:
        expected = _expected(expected, op)
    got, new_body = _reader(after)
    assert _eq(got, expected), f"parsed {got!r}, expected {expected!r}"
    assert list(got) == list(expected), "key order changed"
    if not any(isinstance(op, ReplaceBody) for op in ops):
        assert after[span_of(after).body :] == before[span_of(before).body :]
    assert after.startswith("﻿") == before.startswith("﻿")
    if "\r\n" in before:
        assert after.count("\n") == after.count("\r\n"), "a bare LF in a CRLF file"
    else:
        assert "\r" not in after


# --- the table: every shape crossed with the operations -----------------------

CASES: list[tuple[str, list, str]] = [
    # (shape, ops, outcome): outcome is "changed", "unchanged" or "refused"
    ("doc-field-notes", [Set("title", "Field notes, second draft")], "changed"),
    ("doc-field-notes", [Set("flag", "yes")], "changed"),
    ("doc-field-notes", [Set("flag", "no")], "unchanged"),
    ("doc-field-notes", [Append("tags", "gamma")], "changed"),
    ("doc-field-notes", [Remove("tags", "alpha")], "changed"),
    ("doc-field-notes", [Set("links[0].relation", "supersedes")], "changed"),
    ("doc-field-notes", [AddSubkey("links[0]", "note", "x")], "changed"),
    ("doc-field-notes", [Unset("type")], "changed"),
    ("doc-field-notes", [Set("importance", 3)], "changed"),
    ("doc-field-notes", [ReplaceBody("New body.")], "changed"),
    ("doc-field-notes", [Set("tags", ["alpha", "beta"])], "unchanged"),
    ("doc-field-notes", [Set("tags", ["beta", "gamma"])], "changed"),
    (
        "doc-field-notes",
        [Set("links", [{"target": "other-entry", "relation": "related"}, {"target": "x"}])],
        "changed",
    ),
    ("doc-legacy-links", [Append("links", {"target": "bar", "relation": "related"})], "changed"),
    ("doc-legacy-links", [Set("links[0].type", "cites")], "changed"),
    (
        "doc-legacy-links",
        [Remove("links", {"to": "foo", "type": "related", "since": 2020})],
        "changed",
    ),
    ("crlf", [Set("title", "New title")], "changed"),
    ("crlf", [Set("status", "draft")], "changed"),
    ("crlf", [Append("tags", "gamma")], "changed"),
    ("crlf", [Set("date", "2026-01-15")], "unchanged"),
    ("crlf", [ReplaceBody("Line one.\nLine two.")], "changed"),
    ("bom", [Set("title", "Still a BOM")], "changed"),
    ("bom", [Append("tags", "c")], "changed"),
    ("bom", [Unset("tags")], "changed"),
    ("quoted", [Set("title", "it's new")], "changed"),
    ("quoted", [Set("summary", 'say "bye"')], "changed"),
    ("yaml11-words", [Set("status", "no")], "changed"),
    ("yaml11-words", [Set("other", True)], "changed"),
    ("yaml11-words", [Set("nil", None)], "unchanged"),
    ("yaml11-words", [Set("other", "yes")], "unchanged"),
    ("block-scalars", [Unset("summary")], "changed"),
    ("block-scalars", [Unset("notes")], "changed"),
    ("block-scalars", [Set("notes", "line one\nline three\n")], "changed"),
    ("block-scalars", [Set("summary", "a new folded paragraph\n")], "changed"),
    ("block-scalars", [Set("next", 2)], "changed"),
    ("multiline-plain", [Set("other", "y")], "changed"),
    ("multiline-plain", [Set("title", "short")], "changed"),
    ("mixed-list-indent", [Append("tags", "c")], "changed"),
    ("mixed-list-indent", [Append("aliases", "z")], "changed"),
    ("mixed-list-indent", [Remove("aliases", "x")], "changed"),
    ("anchor-alias", [Set("plain", "new")], "changed"),
    ("anchor-alias", [Set("base.k", "w")], "refused"),
    ("anchor-alias", [Set("child", {"k": "w"})], "refused"),
    ("anchor-alias", [Set("merged.own", 2)], "refused"),
    ("anchor-alias", [Unset("child")], "refused"),
    ("duplicate-keys", [Set("title", "three")], "refused"),
    ("duplicate-keys", [Set("status", "done")], "refused"),
    ("hugo", [Set("params.author", "John")], "changed"),
    ("hugo", [Set("params.social.mastodon", "@jane")], "changed"),
    ("hugo", [Set("draft", True)], "changed"),
    ("hugo", [Append("tags", "go")], "changed"),
    ("hugo", [Set("date", "2024-03-01T14:30:00+00:00")], "unchanged"),
    ("hugo", [Set("date", "2024-03-02T09:30:00-05:00")], "changed"),
    ("hugo", [ReplaceBody('{{< figure src="/img/b.png" >}}\n\nNew text.')], "changed"),
    ("comment-above-unset", [Unset("legacy")], "changed"),
    ("comment-above-unset", [Set("metadata.source_id", "s-1")], "changed"),
    ("no-final-newline", [ReplaceBody("Other text")], "changed"),
    ("no-final-newline", [Set("title", "U")], "changed"),
    ("odd-spacing", [Set("title", "New")], "changed"),
    ("odd-spacing", [Append("tags", "three")], "changed"),
    ("odd-spacing", [Set("id", "odd")], "unchanged"),
    ("empty-flow", [Append("tags", "a")], "changed"),
    ("empty-flow", [Set("links.k", 1)], "changed"),
    ("empty-flow", [Unset("tags")], "changed"),
    ("dates", [Set("date", "2026-01-15")], "unchanged"),
    ("dates", [Set("date", "2026-02-01")], "changed"),
    ("dates", [Set("updated", "2026-01-17")], "changed"),
    ("dates", [Set("updated", "2026-01-16")], "unchanged"),
    ("dates", [Unset("missing")], "unchanged"),
    ("dates", [Remove("tags", "x")], "unchanged"),
]


def test_every_shape_is_in_the_table():
    """Property 7: each of #730's 17 shapes is exercised."""
    assert len(SHAPES) == 17
    assert {shape for shape, _, _ in CASES} == set(SHAPES)


@pytest.mark.parametrize(
    ("shape", "ops", "outcome"),
    CASES,
    ids=[f"{s}-{i}" for i, (s, _, _) in enumerate(CASES)],
)
def test_operation_contract(shape, ops, outcome):
    before = SHAPES[shape]
    if outcome == "refused":
        with pytest.raises(OperationRefusedError) as raised:
            run(before, *ops)
        assert raised.value.reason
        return
    after, report = run(before, *ops)
    if outcome == "unchanged":
        assert after is before
        assert not report.changed
        assert [r.outcome for r in report.results] == ["unchanged"] * len(ops)
        return
    assert after != before
    assert report.changed
    check_contract(before, ops, after)


# --- exact bytes: quote style, comment column, EOL, BOM, list style -----------


def _diff(before: str, after: str) -> list[str]:
    import difflib

    a, b = before.splitlines(keepends=True), after.splitlines(keepends=True)
    return [
        line
        for line in difflib.unified_diff(a, b, n=0)
        if line[:1] in "+-" and not line.startswith(("+++", "---"))
    ]


def test_doc_example_one_field_edit_keeps_the_comment():
    after, _ = run(SHAPES["doc-field-notes"], Set("title", "Field notes, second draft"))
    assert _diff(SHAPES["doc-field-notes"], after) == [
        "-title: Field notes   # working title\n",
        "+title: Field notes, second draft   # working title\n",
    ]


def test_doc_example_append_leaves_existing_items_alone():
    before = SHAPES["doc-legacy-links"]
    after, _ = run(before, Append("links", {"target": "bar", "relation": "related"}))
    assert _diff(before, after) == ["+- target: bar\n", "+  relation: related\n"]


def test_a_shorter_value_keeps_the_comment_column():
    before = SHAPES["quoted"]
    after, _ = run(before, Set("title", "it's new"))
    line = after.splitlines()[2]
    assert line == "title: 'it''s new'          # c"
    assert line.rindex("#") == before.splitlines()[2].rindex("#")


def test_a_double_quoted_scalar_stays_double_quoted():
    after, _ = run(SHAPES["crlf"], Set("title", "New title"))
    assert _diff(SHAPES["crlf"], after) == [
        '-title: "Quoted title"\r\n',
        '+title: "New title"\r\n',
    ]


def test_a_new_key_goes_last_with_the_files_line_ending():
    after, _ = run(SHAPES["crlf"], Set("status", "draft"))
    assert after.endswith(
        "tags: [alpha, beta]  # trailing\r\nstatus: draft\r\n---\r\n\r\nBody.\r\n"
    )


def test_a_flow_list_append_copies_its_neighbours_quoting():
    after, _ = run(SHAPES["hugo"], Append("tags", "go"))
    assert 'tags: ["hugo", "notes", "go"]\n' in after


def test_an_append_takes_each_lists_own_indent():
    before = SHAPES["mixed-list-indent"]
    after, _ = run(before, Append("tags", "c"), Append("aliases", "z"))
    assert _diff(before, after) == ["+- c\n", "+  - z\n"]


def test_a_nested_set_keeps_four_space_indent():
    before = SHAPES["hugo"]
    after, _ = run(before, Set("params.social.mastodon", "@jane"))
    assert _diff(before, after) == ['+        mastodon: "@jane"\n']


def test_a_string_yaml11_would_misread_is_quoted_when_emitted():
    before = SHAPES["yaml11-words"]
    after, _ = run(before, Set("status", "no"))
    assert _diff(before, after) == ["-status: draft\n", '+status: "no"\n']
    assert "flag: no\nother: yes\nnil: null\n" in after


def test_untouched_yes_no_null_stay_bare():
    before = SHAPES["yaml11-words"]
    after, _ = run(before, Set("status", "done"))
    assert "flag: no\nother: yes\nnil: null\n" in after


def test_the_bom_survives_every_operation():
    before = SHAPES["bom"]
    after, _ = run(before, Set("title", "Still"), Append("tags", "c"), ReplaceBody("New."))
    assert after.startswith("﻿---\n")


def test_unset_of_a_folded_block_scalar_keeps_the_next_key():
    """#730 section 1, note 2: a block scalar's end mark is at the start of the
    line after it, and the first spike's unset ate the next key."""
    before = SHAPES["block-scalars"]
    after, _ = run(before, Unset("summary"))
    assert _diff(before, after) == [
        "-summary: >\n",
        "-  a folded\n",
        "-  paragraph\n",
    ]
    assert "\nnotes: |\n  line one\n  line two\nnext: 1\n" in after


def test_unset_of_a_literal_block_scalar_keeps_the_next_key():
    before = SHAPES["block-scalars"]
    after, _ = run(before, Unset("notes"))
    assert _diff(before, after) == ["-notes: |\n", "-  line one\n", "-  line two\n"]


def test_set_of_a_literal_block_scalar_keeps_literal_style():
    before = SHAPES["block-scalars"]
    after, _ = run(before, Set("notes", "line one\nline three\n"))
    assert _diff(before, after) == ["-  line two\n", "+  line three\n"]


def test_unset_leaves_the_comment_above_the_key():
    before = SHAPES["comment-above-unset"]
    after, _ = run(before, Unset("legacy"))
    assert _diff(before, after) == ["-legacy: old\n"]


def test_unset_of_a_list_does_not_take_the_comment_after_it():
    """A block sequence's end mark runs past the comment line below it."""
    before = "---\nid: c\ntags:\n- a\n- b\n# about status\nstatus: x\n---\n\nT.\n"
    after, _ = run(before, Unset("tags"))
    assert _diff(before, after) == ["-tags:\n", "-- a\n", "-- b\n"]


def test_removing_the_last_item_of_a_block_list_leaves_an_empty_list():
    before = "---\nid: c\ntags:\n- a\n---\n\nT.\n"
    after, _ = run(before, Remove("tags", "a"))
    assert _reader(after)[0]["tags"] == []


def test_a_set_of_a_list_is_reduced_to_item_edits():
    before = SHAPES["doc-legacy-links"]
    new_links = [
        {"to": "foo", "type": "related", "since": 2020},
        {"target": "bar", "relation": "related"},
    ]
    after, _ = run(before, Set("links", new_links))
    assert _diff(before, after) == ["+- target: bar\n", "+  relation: related\n"]


def test_add_subkey_inserts_one_line_at_the_items_indent():
    before = SHAPES["doc-field-notes"]
    after, _ = run(before, AddSubkey("links[0]", "note", "x"))
    assert _diff(before, after) == ["+  note: x\n"]


def test_add_subkey_refuses_an_existing_key_with_another_value():
    with pytest.raises(OperationRefusedError):
        run(SHAPES["doc-field-notes"], AddSubkey("links[0]", "relation", "other"))


def test_replace_body_keeps_the_leading_blank_line_and_missing_newline():
    before = SHAPES["no-final-newline"]
    after, _ = run(before, ReplaceBody("Other text"))
    assert after == "---\nid: nonl\ntitle: T\n---\n\nOther text"


def test_replace_body_in_a_crlf_file_writes_crlf():
    after, _ = run(SHAPES["crlf"], ReplaceBody("Line one.\nLine two."))
    assert after.endswith("---\r\n\r\nLine one.\r\nLine two.\r\n")


def test_replace_body_with_the_readers_form_is_unchanged():
    before = SHAPES["doc-field-notes"]
    body = _reader(before)[1]
    after, report = run(before, ReplaceBody(body))
    assert after is before and not report.changed


def test_a_date_string_set_keeps_the_date_plain():
    before = SHAPES["dates"]
    after, _ = run(before, Set("date", "2026-02-01"), Set("updated", "2026-01-17"))
    assert _diff(before, after) == [
        "-date: 2026-01-15\n",
        "-updated: '2026-01-16'\n",
        "+date: 2026-02-01\n",
        "+updated: '2026-01-17'\n",
    ]


def test_a_number_into_a_plain_string_field_is_quoted():
    before = SHAPES["doc-field-notes"]
    after, _ = run(before, Set("type", "123"))
    assert '\ntype: "123"\n' in after
    assert _reader(after)[0]["type"] == "123"


def test_several_operations_in_one_call():
    before = SHAPES["doc-field-notes"]
    ops = [Set("title", "T2"), Append("tags", "gamma"), Unset("flag"), ReplaceBody("B.")]
    after, report = run(before, *ops)
    assert [r.outcome for r in report.results] == ["changed"] * 4
    check_contract(before, ops, after)


# --- refusals ---------------------------------------------------------------


@pytest.mark.parametrize(
    "text",
    [
        '+++\ntitle = "TOML"\n+++\n\nText.\n',
        '{\n  "title": "JSON"\n}\n\nText.\n',
        "No frontmatter at all.\n",
    ],
    ids=["toml", "json", "none"],
)
def test_no_yaml_frontmatter_is_refused_untouched(text):
    with pytest.raises(OperationRefusedError) as raised:
        apply(text, [Set("title", "x")], span_of(text))
    assert raised.value.reason


def test_a_flow_style_root_mapping_is_refused():
    text = "---\n{id: x, title: y}\n---\n\nText.\n"
    with pytest.raises(OperationRefusedError):
        run(text, Set("title", "z"))


def test_an_append_to_a_scalar_is_refused():
    with pytest.raises(OperationRefusedError):
        run(SHAPES["doc-field-notes"], Append("title", "x"))


def test_the_anchor_refusal_names_the_reason():
    with pytest.raises(OperationRefusedError) as raised:
        run(SHAPES["anchor-alias"], Set("child", {"k": "w"}))
    assert "anchor" in raised.value.reason or "alias" in raised.value.reason


def test_the_duplicate_key_refusal_names_the_key():
    """Refused by the module's own check, in one line a person can read; not
    by ruamel's multi-line DuplicateKeyError, which the loader would raise
    anyway."""
    with pytest.raises(OperationRefusedError) as raised:
        run(SHAPES["duplicate-keys"], Set("status", "done"))
    assert "duplicate key 'title'" in raised.value.reason
    assert "\n" not in raised.value.reason


# --- property 5: a no-op returns the very same object ------------------------


@pytest.mark.parametrize("shape", sorted(SHAPES))
def test_no_operations_return_the_input_object(shape):
    text = SHAPES[shape]
    after, report = apply(text, [], span_of(text))
    assert after is text and not report.changed


@pytest.mark.parametrize("shape", sorted(set(SHAPES) - {"anchor-alias", "duplicate-keys"}))
def test_an_echo_of_every_value_is_a_no_op(shape):
    """Setting every top-level key to the value the reader gives writes nothing."""
    text = SHAPES[shape]
    meta, body = _reader(text)
    ops = [Set(key, value) for key, value in meta.items()] + [ReplaceBody(body)]
    after, report = run(text, *ops)
    assert after is text
    assert not report.changed


# --- the post-check is the guard (ADR-0042 decision 2) ------------------------


def test_a_narrow_edit_that_fails_the_post_check_is_widened_not_returned(monkeypatch):
    """A narrow edit that also changes bytes it was not asked to change must
    never be returned: the post-check catches it and the key is widened
    item-wise (or the call refuses)."""
    from pyrite.storage import file_operations as fo

    real = fo._narrow_edits

    def corrupt(doc, op):
        edits = real(doc, op)
        # also respell an untouched key: `type: note` -> `type: Note`
        at = doc.text.index("type: note") + len("type: ")
        return [*edits, (at, at + 1, "N")]

    monkeypatch.setattr(fo, "_narrow_edits", corrupt)
    before = SHAPES["doc-field-notes"]
    try:
        after, report = run(before, Append("links", {"target": "x"}))
    except OperationRefusedError:
        return
    assert "type: note\n" in after
    check_contract(before, [Append("links", {"target": "x"})], after)
    assert report.widened == ("links",)


def test_a_narrow_edit_that_breaks_the_value_is_widened(monkeypatch):
    """The post-check compares values too, not only untouched bytes."""
    from pyrite.storage import file_operations as fo

    real = fo._narrow_edits

    def corrupt(doc, op):
        return [(s, e, r.replace("bar", "baz")) for s, e, r in real(doc, op)]

    monkeypatch.setattr(fo, "_narrow_edits", corrupt)
    before = SHAPES["doc-legacy-links"]
    op = Append("links", {"target": "bar", "relation": "related"})
    after, report = run(before, op)
    check_contract(before, [op], after)
    assert report.widened == ("links",)
    # item-wise: the hand-written item, comment and all, is copied by bytes
    assert _diff(before, after) == ["+- target: bar\n", "+  relation: related\n"]


def test_values_equal_is_decision_3():
    assert values_equal("2026-01-15", date(2026, 1, 15))
    assert values_equal(1, 1.0)
    assert not values_equal(True, 1)
    assert values_equal({"a": 1, "b": 2}, {"b": 2, "a": 1})
    assert not values_equal([1, 2], [2, 1])
    assert not values_equal("5", 5)


# --- the oracle can see failures: candidate A as a control --------------------


def _round_trip(text: str, key: str, value: Any) -> str:
    """#730's candidate A: load with ruamel, set, dump. Rejected by the spike
    for respelling bytes nobody asked to change."""
    from pyrite.utils.yaml import dump_yaml, load_yaml

    span = span_of(text)
    data = load_yaml(text[span.start : span.end])
    data[key] = value
    return text[: span.start] + dump_yaml(data) + text[span.end :]


@pytest.mark.parametrize(
    ("shape", "key", "value"),
    [
        ("hugo", "draft", True),  # re-indents the 4-space params map
        ("yaml11-words", "status", "done"),  # respells `nil: null` as `nil:`
        ("odd-spacing", "title", "New"),  # collapses `id:    odd`
    ],
)
def test_the_oracle_catches_the_round_trip(shape, key, value):
    """The contract check is not vacuous: the round trip fails it where the
    spike saw it change untouched bytes, and apply passes it."""
    before = SHAPES[shape]
    with pytest.raises(AssertionError):
        check_contract(before, [Set(key, value)], _round_trip(before, key, value))
    after, _ = run(before, Set(key, value))
    check_contract(before, [Set(key, value)], after)
